
services:

  ai_worker:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    env_file:
      - .env
    volumes:
      - ./backend/app:/app
    build:
      context: ./backend
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}
    command: python -m app.services.free4gpt.ai_worker
    restart: always

  free-gpt4:
    image: d0ckmg/free-gpt4-web-api
    restart: unless-stopped
    env_file:
      - .env
    command:
      - --enable-gui
      - --password
      - ${PASSWORD_GPT}
      - --port
      - '5500'
    ports:
      - 5500:5500

  db:
    image: postgis/postgis:12-3.4
    env_file:
      - .env
    command: postgres -c 'max_connections=1000'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./app-db-data:/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5070:5051"
    env_file:
      - .env
    depends_on:
      - db
  
  backend:
    container_name: backend_geogesh_v2
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    ports:
      # - "80:80"
      - "72:80"
      - "8882:8888"
    restart: always
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    command: /start-reload.sh
    volumes:
      - ./backend/app:/app
    depends_on:
      - db

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    command: "redis-server --appendonly yes --port 6480 --timeout 300 --tcp-keepalive 60"
    volumes:
      - ./redis:/data


  redis-commander:
    image: "rediscommander/redis-commander:latest"
    restart: unless-stopped
    ports:
      - 8043:8081
    environment:
      - "REDIS_HOSTS=local:redis:6480"
    depends_on:
      - "redis"
#  redis:
#    image: redis:alpine
#    restart: always
#    command: "redis-server --appendonly yes --port 6379"
#    volumes:
#      - ./redis:/data

#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    restart: always
#    environment:
#      - REDIS_HOSTS=local:redis:6379
#    ports:
#      - "8070:8081"  # Открытый порт для Redis Commander
#    depends_on:
#      - "redis"



volumes:
  app-db-data:

