user  root;
worker_processes auto;

events {
}

http {

    server {
        listen 80;
        server_name avatars.axas.ru;

    	location /.well-known/acme-challenge/ {
		 root /var/www/certbot/;
    	} # Нужно для автообновление сертификата через  webroot

        location / {
            return 301 https://$host$request_uri;
        }
    }


}

# sudo snap install --classic certbot               install
# certbot certonly --webroot  -w /var/www/certbot -d api.example.com --dry_run          test renew
