"""promo order

Revision ID: 03318fc3b002
Revises: 59927ceee380
Create Date: 2024-10-23 10:54:08.856960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03318fc3b002'
down_revision = '59927ceee380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promoorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promoorder_created'), 'promoorder', ['created'], unique=False)
    op.create_index(op.f('ix_promoorder_id'), 'promoorder', ['id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.drop_index(op.f('ix_promoorder_id'), table_name='promoorder')
    op.drop_index(op.f('ix_promoorder_created'), table_name='promoorder')
    op.drop_table('promoorder')
    # ### end Alembic commands ###
