"""empty message

Revision ID: 068c91db4b1c
Revises: bfee7ec1b2c7
Create Date: 2023-02-21 11:25:04.031381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068c91db4b1c'
down_revision = 'bfee7ec1b2c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacktel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tel', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacktel_id'), 'blacktel', ['id'], unique=False)
    op.create_index(op.f('ix_blacktel_tel'), 'blacktel', ['tel'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blacktel_tel'), table_name='blacktel')
    op.drop_index(op.f('ix_blacktel_id'), table_name='blacktel')
    op.drop_table('blacktel')
    # ### end Alembic commands ###
