"""empty message

Revision ID: 08565415d833
Revises: 9263cca875ef
Create Date: 2023-10-16 10:55:27.788207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.enums.mod_status import ModStatus

# revision identifiers, used by Alembic.
revision = '08565415d833'
down_revision = '9263cca875ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    mod_status = postgresql.ENUM(ModStatus, name="status")
    mod_status.create(op.get_bind(), checkfirst=True)

    op.add_column('order', sa.Column('status', mod_status, server_default='created', nullable=False))
    op.add_column('order', sa.Column('moderation_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'moderation_comment')
    op.drop_column('order', 'status')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
