"""add like profile

Revision ID: 08cb7b23017f
Revises: e59ce7c15c15
Create Date: 2024-07-11 07:36:24.486852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08cb7b23017f'
down_revision = 'e59ce7c15c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profilelike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liker_dating_profile_id', sa.Integer(), nullable=True),
    sa.Column('liked_dating_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liked_dating_profile_id'], ['datingprofile.id'], ),
    sa.ForeignKeyConstraint(['liker_dating_profile_id'], ['datingprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profilelike_id'), 'profilelike', ['id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_profilelike_id'), table_name='profilelike')
    op.drop_table('profilelike')
    # ### end Alembic commands ###
