"""empty message

Revision ID: 08f842bb4b45
Revises: be05e07355c2
Create Date: 2025-05-07 07:45:18.801027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f842bb4b45'
down_revision = 'be05e07355c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('excursion', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('excursion', 'address')
    # ### end Alembic commands ###
