"""detected_os for device

Revision ID: 0a226d0cdbb6
Revises: 4343809fdf7c
Create Date: 2022-06-09 13:20:58.672653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a226d0cdbb6'
down_revision = '4343809fdf7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
