"""dellp extra

Revision ID: 0ab8c136bcfa
Revises: f47a940da1c1
Create Date: 2024-12-03 11:31:41.584987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ab8c136bcfa'
down_revision = 'f47a940da1c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messageextradatum_id', table_name='messageextradatum')
    op.drop_index('ix_messageextradatum_is_delete', table_name='messageextradatum')
    op.drop_index('ix_messageextradatum_member_id', table_name='messageextradatum')
    op.drop_index('ix_messageextradatum_message_id', table_name='messageextradatum')
    op.drop_table('messageextradatum')
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.create_table('messageextradatum',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('read', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_delete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name='messageextradatum_member_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name='messageextradatum_message_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='messageextradatum_pkey')
    )
    op.create_index('ix_messageextradatum_message_id', 'messageextradatum', ['message_id'], unique=False)
    op.create_index('ix_messageextradatum_member_id', 'messageextradatum', ['member_id'], unique=False)
    op.create_index('ix_messageextradatum_is_delete', 'messageextradatum', ['is_delete'], unique=False)
    op.create_index('ix_messageextradatum_id', 'messageextradatum', ['id'], unique=False)
    # ### end Alembic commands ###
