"""rg_ext_hash_for_hotelbooking

Revision ID: 0bf3b884fb3d
Revises: e2f47031db06
Create Date: 2025-06-02 06:17:38.082595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf3b884fb3d'
down_revision = 'e2f47031db06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notincludedtax',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_booking_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_booking_id'], ['hotelbooking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notincludedtax_hotel_booking_id'), 'notincludedtax', ['hotel_booking_id'], unique=False)
    op.create_index(op.f('ix_notincludedtax_id'), 'notincludedtax', ['id'], unique=False)
    op.add_column('hotelbooking', sa.Column('rg_ext_hash', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotelbooking', 'rg_ext_hash')
    op.drop_index(op.f('ix_notincludedtax_id'), table_name='notincludedtax')
    op.drop_index(op.f('ix_notincludedtax_hotel_booking_id'), table_name='notincludedtax')
    op.drop_table('notincludedtax')
    # ### end Alembic commands ###
