"""add dating facts and music

Revision ID: 0db398defce2
Revises: ecda87b0b1f8
Create Date: 2024-07-09 08:15:17.766823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db398defce2'
down_revision = 'ecda87b0b1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facts_name', sa.String(), nullable=True),
    sa.Column('parent_facts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_facts_id'], ['interests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facts_id'), 'facts', ['id'], unique=False)
    op.create_table('genremusic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_music_name', sa.String(), nullable=True),
    sa.Column('parent_genre_music_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_genre_music_id'], ['interests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genremusic_id'), 'genremusic', ['id'], unique=False)
    op.create_table('profilefacts',
    sa.Column('dating_profile_id', sa.Integer(), nullable=False),
    sa.Column('subfacts_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dating_profile_id'], ['datingprofile.id'], ),
    sa.ForeignKeyConstraint(['subfacts_id'], ['facts.id'], ),
    sa.PrimaryKeyConstraint('dating_profile_id', 'subfacts_id')
    )
    op.create_table('profilegenremusic',
    sa.Column('dating_profile_id', sa.Integer(), nullable=False),
    sa.Column('sub_genre_music_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dating_profile_id'], ['datingprofile.id'], ),
    sa.ForeignKeyConstraint(['sub_genre_music_id'], ['genremusic.id'], ),
    sa.PrimaryKeyConstraint('dating_profile_id', 'sub_genre_music_id')
    )
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('profilegenremusic')
    op.drop_table('profilefacts')
    op.drop_index(op.f('ix_genremusic_id'), table_name='genremusic')
    op.drop_table('genremusic')
    op.drop_index(op.f('ix_facts_id'), table_name='facts')
    op.drop_table('facts')
    # ### end Alembic commands ###
