"""empty message

Revision ID: 0faf601e0cbc
Revises: df06b318ef54
Create Date: 2023-08-16 09:30:43.703445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0faf601e0cbc'
down_revision = 'df06b318ef54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_info_user_id'), 'info', ['user_id'], unique=False)
    op.create_foreign_key(None, 'info', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'info', type_='foreignkey')
    op.drop_index(op.f('ix_info_user_id'), table_name='info')
    op.drop_column('info', 'user_id')
    # ### end Alembic commands ###
