"""add dating profile two

Revision ID: 120d8c14105a
Revises: 3ef27367b2f0
Create Date: 2024-07-04 07:06:48.566482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120d8c14105a'
down_revision = '3ef27367b2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest_name', sa.String(), nullable=True),
    sa.Column('parent_interest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_interest_id'], ['interests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interests_id'), 'interests', ['id'], unique=False)
    op.create_table('dating_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('films', sa.String(), nullable=True),
    sa.Column('book', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('work', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dating_profile_id'), 'dating_profile', ['id'], unique=False)
    op.create_table('profile_interests',
    sa.Column('dating_profile_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dating_profile_id'], ['dating_profile.id'], ),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ),
    sa.PrimaryKeyConstraint('dating_profile_id', 'interest_id')
    )
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('profile_interests')
    op.drop_index(op.f('ix_dating_profile_id'), table_name='dating_profile')
    op.drop_table('dating_profile')
    op.drop_index(op.f('ix_interests_id'), table_name='interests')
    op.drop_table('interests')
    # ### end Alembic commands ###
