"""empty message

Revision ID: 1415b2a1f21a
Revises: 2638fa1a7377
Create Date: 2025-04-18 07:53:47.520584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1415b2a1f21a'
down_revision = '2638fa1a7377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE groupstatus ADD VALUE 'FINISHED' AFTER 'COMPLETED'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE excursiongroup ALTER COLUMN status TYPE TEXT")
    op.execute("DROP TYPE groupstatus")
    op.execute("CREATE TYPE groupstatus AS ENUM ('available', 'completed')")
    op.execute("""
            ALTER TABLE excursiongroup 
            ALTER COLUMN status TYPE groupstatus 
            USING status::text::groupstatus
        """)
    # ### end Alembic commands ###
