"""add colum noti

Revision ID: 162fd6e00259
Revises: 6dc0d83fd934
Create Date: 2024-12-12 12:59:01.438820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162fd6e00259'
down_revision = '6dc0d83fd934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ratingweights_user_id_fkey', 'ratingweights', type_='foreignkey')
    op.drop_constraint('ratingweights_profile_id_fkey', 'ratingweights', type_='foreignkey')
    op.create_foreign_key(None, 'ratingweights', 'datingprofile', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ratingweights', 'datingprofile', ['profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratingweights', type_='foreignkey')
    op.drop_constraint(None, 'ratingweights', type_='foreignkey')
    op.create_foreign_key('ratingweights_profile_id_fkey', 'ratingweights', 'datingprofile', ['profile_id'], ['id'])
    op.create_foreign_key('ratingweights_user_id_fkey', 'ratingweights', 'datingprofile', ['user_id'], ['id'])
  
    # ### end Alembic commands ###
