"""Rename Report to UserReport

Revision ID: 189ca4dc59b8
Revises: 826ceafc44e0
Create Date: 2022-06-27 12:50:14.536474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '189ca4dc59b8'
down_revision = '826ceafc44e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('is_satisfy', sa.Boolean(), nullable=True),
    sa.Column('reason', postgresql.ENUM('spam', 'nudity', 'hostility', 'violence', 'bullying', 'forbidden_product', 'intellectual_property_rights', 'suicide', 'eating_disorder', 'deceit', 'fake', name='reason', create_type=False), nullable=True),
    sa.Column('additional_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userreport_id'), 'userreport', ['id'], unique=False)
    op.drop_index('ix_report_id', table_name='report')
    op.drop_table('report')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_satisfy', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.ENUM('spam', 'nudity', 'hostility', 'violence', 'bullying', 'forbidden_product', 'intellectual_property_rights', 'suicide', 'eating_disorder', 'deceit', 'fake', name='reason'), autoincrement=False, nullable=True),
    sa.Column('additional_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['user.id'], name='report_object_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['user.id'], name='report_subject_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='report_pkey')
    )
    op.create_index('ix_report_id', 'report', ['id'], unique=False)
    op.drop_index(op.f('ix_userreport_id'), table_name='userreport')
    op.drop_table('userreport')
    # ### end Alembic commands ###
