"""OrderView

Revision ID: 1fe4eb47cff6
Revises: 0112920630c6
Create Date: 2024-11-25 07:25:04.886741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe4eb47cff6'
down_revision = '0112920630c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('is_viewed', sa.Boolean(), server_default='True', nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderview_created'), 'orderview', ['created'], unique=False)
    op.create_index(op.f('ix_orderview_id'), 'orderview', ['id'], unique=False)
    op.create_index(op.f('ix_orderview_order_id'), 'orderview', ['order_id'], unique=False)
    op.create_index(op.f('ix_orderview_user_id'), 'orderview', ['user_id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    op.add_column('order', sa.Column('views_counter', sa.Integer(), server_default='0', nullable=True))
    op.create_index(op.f('ix_order_views_counter'), 'order', ['views_counter'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_views_counter'), table_name='order')
    op.drop_column('order', 'views_counter')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.drop_index(op.f('ix_orderview_user_id'), table_name='orderview')
    op.drop_index(op.f('ix_orderview_order_id'), table_name='orderview')
    op.drop_index(op.f('ix_orderview_id'), table_name='orderview')
    op.drop_index(op.f('ix_orderview_created'), table_name='orderview')
    op.drop_table('orderview')
    # ### end Alembic commands ###
