"""empty message

Revision ID: 21a1e70493b8
Revises: a1eeec07074d
Create Date: 2023-02-25 10:32:11.044548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a1e70493b8'
down_revision = 'a1eeec07074d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'region')
    # ### end Alembic commands ###
