"""Add column  to User model

Revision ID: 22caf7e883bf
Revises: 518669587a45
Create Date: 2022-05-19 14:25:07.501675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22caf7e883bf'
down_revision = '518669587a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_available')
    # ### end Alembic commands ###
