"""empty message

Revision ID: 261252013c58
Revises: 08f842bb4b45
Create Date: 2025-05-13 13:39:50.708331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261252013c58'
down_revision = '08f842bb4b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snowmobilebooking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('snowmobile_quantity', sa.Integer(), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=False),
    sa.Column('ended', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snowmobilebooking_id'), 'snowmobilebooking', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snowmobilebooking_id'), table_name='snowmobilebooking')
    op.drop_table('snowmobilebooking')
    # ### end Alembic commands ###
