"""empty message

Revision ID: 2638fa1a7377
Revises: c73bef42745b
Create Date: 2025-04-18 05:29:29.684267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2638fa1a7377'
down_revision = 'c73bef42745b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('excursionbooking_comment_key', 'excursionbooking', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('excursionbooking_comment_key', 'excursionbooking', ['comment'])
    # ### end Alembic commands ###
