"""empty message

Revision ID: 280beb3061af
Revises: 7753fb1ddd8b
Create Date: 2023-01-21 15:19:13.674746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280beb3061af'
down_revision = '7753fb1ddd8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.add_column('user', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'category_id')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
