"""sub_category_tree

Revision ID: 2813e41c0e68
Revises: 6b07e955bfe1
Create Date: 2024-07-02 13:26:25.815172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2813e41c0e68'
down_revision = '6b07e955bfe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('userinterest', sa.Column('sub_interest_id', sa.Integer(), nullable=True))
    op.drop_index('ix_userinterest_interest_id', table_name='userinterest')
    op.create_index(op.f('ix_userinterest_sub_interest_id'), 'userinterest', ['sub_interest_id'], unique=False)
    op.drop_constraint('userinterest_interest_id_fkey', 'userinterest', type_='foreignkey')
    op.create_foreign_key(None, 'userinterest', 'subinterest', ['sub_interest_id'], ['id'], ondelete='CASCADE')
    op.drop_column('userinterest', 'interest_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinterest', sa.Column('interest_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'userinterest', type_='foreignkey')
    op.create_foreign_key('userinterest_interest_id_fkey', 'userinterest', 'interest', ['interest_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_userinterest_sub_interest_id'), table_name='userinterest')
    op.create_index('ix_userinterest_interest_id', 'userinterest', ['interest_id'], unique=False)
    op.drop_column('userinterest', 'sub_interest_id')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
