"""Fix user agent column

Revision ID: 2831a40e755c
Revises: 1bcabf73e0c3
Create Date: 2022-06-07 08:43:30.765658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2831a40e755c'
down_revision = '1bcabf73e0c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'user_agent',
               existing_type=postgresql.INET(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'user_agent',
               existing_type=sa.String(),
               type_=postgresql.INET(),
               existing_nullable=True)
    # ### end Alembic commands ###
