"""last_message

Revision ID: 2dc044ddf59e
Revises: abc1a3a045b5
Create Date: 2022-08-22 12:48:40.454776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc044ddf59e'
down_revision = 'abc1a3a045b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_last_message_id_fkey', 'chat', type_='foreignkey')
    op.drop_column('chat', 'last_message_id')
    op.add_column('member', sa.Column('last_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'member', 'message', ['last_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.drop_column('member', 'last_message_id')
    op.add_column('chat', sa.Column('last_message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('chat_last_message_id_fkey', 'chat', 'message', ['last_message_id'], ['id'])
    # ### end Alembic commands ###
