"""empty message

Revision ID: 2ebd5f94dea6
Revises: 359b25af3e2a
Create Date: 2025-05-19 08:23:07.407165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebd5f94dea6'
down_revision = '359b25af3e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiogideimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('audio_gide_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audio_gide_id'], ['audioguide.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audiogideimage_audio_gide_id'), 'audiogideimage', ['audio_gide_id'], unique=False)
    op.create_index(op.f('ix_audiogideimage_id'), 'audiogideimage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audiogideimage_id'), table_name='audiogideimage')
    op.drop_index(op.f('ix_audiogideimage_audio_gide_id'), table_name='audiogideimage')
    op.drop_table('audiogideimage')
    # ### end Alembic commands ###
