"""add colum noti

Revision ID: 2ecd7ba75731
Revises: 162fd6e00259
Create Date: 2024-12-13 07:35:04.450597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ecd7ba75731'
down_revision = '162fd6e00259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('member_last_message_id_fkey', 'member', type_='foreignkey')
    op.create_foreign_key(None, 'member', 'message', ['last_message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.create_foreign_key('member_last_message_id_fkey', 'member', 'message', ['last_message_id'], ['id'])
    # ### end Alembic commands ###
