"""empty message

Revision ID: 2f66851ac5dd
Revises: f0eecd7a8a7d
Create Date: 2023-09-29 14:32:35.418063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f66851ac5dd'
down_revision = 'f0eecd7a8a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('button_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adv_id'), 'adv', ['id'], unique=False)
    op.create_table('advslide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('adv_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adv_id'], ['adv.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advslide_adv_id'), 'advslide', ['adv_id'], unique=False)
    op.create_index(op.f('ix_advslide_id'), 'advslide', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_advslide_id'), table_name='advslide')
    op.drop_index(op.f('ix_advslide_adv_id'), table_name='advslide')
    op.drop_table('advslide')
    op.drop_index(op.f('ix_adv_id'), table_name='adv')
    op.drop_table('adv')
    # ### end Alembic commands ###
