"""Add topic FK to hashtag model

Revision ID: 308512aa84cd
Revises: 89757a082286
Create Date: 2022-06-10 08:05:27.960310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308512aa84cd'
down_revision = '89757a082286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'hashtag', 'topic', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hashtag', type_='foreignkey')
    # ### end Alembic commands ###
