"""remove shape and colors from user model

Revision ID: 35547fb182eb
Revises: 49a76f07d63c
Create Date: 2022-05-11 12:49:14.075494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35547fb182eb'
down_revision = '49a76f07d63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'shape')
    op.drop_column('user', 'color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('color', postgresql.ENUM('gray', 'black', 'yellow', 'brown', 'blue', 'red', 'orange', 'green', name='color'), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('shape', postgresql.ENUM('square', 'triangle', 'circle', 'polyline', name='shape'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
