"""empty message

Revision ID: 359b25af3e2a
Revises: 261252013c58
Create Date: 2025-05-19 07:46:20.081953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359b25af3e2a'
down_revision = '261252013c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audioguide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audioguide_created'), 'audioguide', ['created'], unique=False)
    op.create_index(op.f('ix_audioguide_id'), 'audioguide', ['id'], unique=False)
    op.create_table('audioguidefile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio', sa.String(), nullable=False),
    sa.Column('audio_guide_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audio_guide_id'], ['audioguide.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audioguidefile_audio_guide_id'), 'audioguidefile', ['audio_guide_id'], unique=False)
    op.create_index(op.f('ix_audioguidefile_id'), 'audioguidefile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audioguidefile_id'), table_name='audioguidefile')
    op.drop_index(op.f('ix_audioguidefile_audio_guide_id'), table_name='audioguidefile')
    op.drop_table('audioguidefile')
    op.drop_index(op.f('ix_audioguide_id'), table_name='audioguide')
    op.drop_index(op.f('ix_audioguide_created'), table_name='audioguide')
    op.drop_table('audioguide')
    # ### end Alembic commands ###
