"""No Mailing Model

Revision ID: 38fed0f6e6cc
Revises: c3370e5224d2
Create Date: 2022-07-08 11:21:14.331473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38fed0f6e6cc'
down_revision = 'c3370e5224d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nomailingentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nomailingentry_id'), 'nomailingentry', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nomailingentry_id'), table_name='nomailingentry')
    op.drop_table('nomailingentry')
    # ### end Alembic commands ###
