"""empty message

Revision ID: 392b8bde99d3
Revises: 5724767f21bf
Create Date: 2025-04-15 13:28:38.337618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392b8bde99d3'
down_revision = '5724767f21bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('excursionreview', sa.Column('id', sa.String(), nullable=False))
    op.drop_index('ix_excursionreview_review_id', table_name='excursionreview')
    op.create_index(op.f('ix_excursionreview_id'), 'excursionreview', ['id'], unique=False)
    op.drop_column('excursionreview', 'review_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('excursionreview', sa.Column('review_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_excursionreview_id'), table_name='excursionreview')
    op.create_index('ix_excursionreview_review_id', 'excursionreview', ['review_id'], unique=False)
    op.drop_column('excursionreview', 'id')
    # ### end Alembic commands ###
