"""empty message

Revision ID: 3a0f259ca98f
Revises: f3c5413a79dd
Create Date: 2025-04-16 05:33:09.690127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a0f259ca98f'
down_revision = 'f3c5413a79dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE sequencename = 'excursionreview_id_seq') THEN
                CREATE SEQUENCE excursionreview_id_seq;
                -- Устанавливаем начальное значение
                PERFORM setval('excursionreview_id_seq', COALESCE((SELECT MAX(id) FROM excursionreview), 1));
            END IF;
        END $$;
        """)

    # 2. Добавляем новый столбец с временным именем
    op.add_column('excursionreview',
                  sa.Column('new_id', sa.Integer(),
                            server_default=sa.text("nextval('excursionreview_id_seq'::regclass)")))

    # 3. Обновляем новый столбец значениями из старого ID
    op.execute("UPDATE excursionreview SET new_id = id")

    # 4. Удаляем старый столбец
    op.drop_column('excursionreview', 'id')

    # 5. Переименовываем new_id → id
    op.alter_column('excursionreview', 'new_id', new_column_name='id')

    # 6. Устанавливаем как PRIMARY KEY
    op.execute("ALTER TABLE excursionreview ADD PRIMARY KEY (id)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('excursionreview',
                  sa.Column('old_id', sa.Integer()))
    op.execute("UPDATE excursionreview SET old_id = id")
    op.drop_column('excursionreview', 'id')
    op.alter_column('excursionreview', 'old_id', new_column_name='id')
    # ### end Alembic commands ###
