"""empty message

Revision ID: 3d6e077dfda0
Revises: 82e911f24481
Create Date: 2023-03-07 06:07:06.939842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6e077dfda0'
down_revision = '82e911f24481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacktel', sa.Column('name', sa.String(), nullable=True))
    op.add_column('blacktel', sa.Column('comment', sa.String(), nullable=True))
    op.alter_column('user', 'show_tel',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('whitetel', sa.Column('name', sa.String(), nullable=True))
    op.add_column('whitetel', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whitetel', 'comment')
    op.drop_column('whitetel', 'name')
    op.alter_column('user', 'show_tel',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('blacktel', 'comment')
    op.drop_column('blacktel', 'name')
    # ### end Alembic commands ###
