"""add fix event

Revision ID: 3ea7058ead93
Revises: 7b1e64750a08
Create Date: 2024-07-24 12:48:29.664369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea7058ead93'
down_revision = '7b1e64750a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interest_id'), 'interest', ['id'], unique=False)
    op.create_table('userinterest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interest.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userinterest_id'), 'userinterest', ['id'], unique=False)
    op.create_index(op.f('ix_userinterest_interest_id'), 'userinterest', ['interest_id'], unique=False)
    op.create_index(op.f('ix_userinterest_user_id'), 'userinterest', ['user_id'], unique=False)
    op.create_table('eventfeedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('answer_text', sa.String(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventfeedback_event_id'), 'eventfeedback', ['event_id'], unique=False)
    op.create_index(op.f('ix_eventfeedback_id'), 'eventfeedback', ['id'], unique=False)
    op.create_index(op.f('ix_eventfeedback_user_id'), 'eventfeedback', ['user_id'], unique=False)
    op.create_table('eventinterest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interest_id'], ['interest.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventinterest_event_id'), 'eventinterest', ['event_id'], unique=False)
    op.create_index(op.f('ix_eventinterest_id'), 'eventinterest', ['id'], unique=False)
    op.create_index(op.f('ix_eventinterest_interest_id'), 'eventinterest', ['interest_id'], unique=False)
    op.create_table('eventperiod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('ended', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventperiod_ended'), 'eventperiod', ['ended'], unique=False)
    op.create_index(op.f('ix_eventperiod_event_id'), 'eventperiod', ['event_id'], unique=False)
    op.create_index(op.f('ix_eventperiod_id'), 'eventperiod', ['id'], unique=False)
    op.create_index(op.f('ix_eventperiod_started'), 'eventperiod', ['started'], unique=False)
    # op.drop_table('spatial_ref_sys')
    op.add_column('event', sa.Column('is_open', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('event', sa.Column('is_draft', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('event', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('pay_link', sa.String(), nullable=True))
    op.add_column('event', sa.Column('is_periodic', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('event', sa.Column('rating', sa.Float(), nullable=True))
    op.create_index(op.f('ix_event_is_periodic'), 'event', ['is_periodic'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_is_periodic'), table_name='event')
    op.drop_column('event', 'rating')
    op.drop_column('event', 'is_periodic')
    op.drop_column('event', 'pay_link')
    op.drop_column('event', 'price')
    op.drop_column('event', 'is_draft')
    op.drop_column('event', 'is_open')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_eventperiod_started'), table_name='eventperiod')
    op.drop_index(op.f('ix_eventperiod_id'), table_name='eventperiod')
    op.drop_index(op.f('ix_eventperiod_event_id'), table_name='eventperiod')
    op.drop_index(op.f('ix_eventperiod_ended'), table_name='eventperiod')
    op.drop_table('eventperiod')
    op.drop_index(op.f('ix_eventinterest_interest_id'), table_name='eventinterest')
    op.drop_index(op.f('ix_eventinterest_id'), table_name='eventinterest')
    op.drop_index(op.f('ix_eventinterest_event_id'), table_name='eventinterest')
    op.drop_table('eventinterest')
    op.drop_index(op.f('ix_eventfeedback_user_id'), table_name='eventfeedback')
    op.drop_index(op.f('ix_eventfeedback_id'), table_name='eventfeedback')
    op.drop_index(op.f('ix_eventfeedback_event_id'), table_name='eventfeedback')
    op.drop_table('eventfeedback')
    op.drop_index(op.f('ix_userinterest_user_id'), table_name='userinterest')
    op.drop_index(op.f('ix_userinterest_interest_id'), table_name='userinterest')
    op.drop_index(op.f('ix_userinterest_id'), table_name='userinterest')
    op.drop_table('userinterest')
    op.drop_index(op.f('ix_interest_id'), table_name='interest')
    op.drop_table('interest')
    # ### end Alembic commands ###
