"""fix chat last message

Revision ID: 422a7961728f
Revises: 0c9afb11e328
Create Date: 2024-07-29 07:20:55.001351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422a7961728f'
down_revision = '0c9afb11e328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.drop_constraint('member_chat_id_fkey', 'member', type_='foreignkey')
    op.drop_constraint('member_first_message_id_fkey', 'member', type_='foreignkey')
    op.create_foreign_key(None, 'member', 'message', ['first_message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'member', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.create_foreign_key('member_first_message_id_fkey', 'member', 'message', ['first_message_id'], ['id'])
    op.create_foreign_key('member_chat_id_fkey', 'member', 'chat', ['chat_id'], ['id'])
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
