"""Add columns is_prof and is_premium to User model

Revision ID: 4343809fdf7c
Revises: 62677f435dcc
Create Date: 2022-06-08 12:09:43.457606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4343809fdf7c'
down_revision = '62677f435dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_prof', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_premium', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_premium')
    op.drop_column('user', 'is_prof')
    # ### end Alembic commands ###
