"""empty message

Revision ID: 47848e2ae192
Revises: fbe7f198cefe
Create Date: 2023-09-18 12:21:49.303798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47848e2ae192'
down_revision = 'fbe7f198cefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventmember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('wait', 'accepted', 'declined', name='acceptingstatus'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventmember_id'), 'eventmember', ['id'], unique=False)
    op.add_column('event', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('max_event_members', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'user', ['user_id'], ['id'])
    op.drop_column('event', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('lon', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'max_event_members')
    op.drop_column('event', 'user_id')
    op.drop_column('event', 'is_private')
    op.drop_index(op.f('ix_eventmember_id'), table_name='eventmember')
    op.drop_table('eventmember')
    # ### end Alembic commands ###
