"""empty message

Revision ID: 483dd06a5882
Revises: 784d2424bb84
Create Date: 2023-04-13 07:47:57.660954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483dd06a5882'
down_revision = '784d2424bb84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('offer',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('created', sa.DateTime(), nullable=False),
    # sa.Column('text', sa.String(), nullable=True),
    # sa.Column('is_winner', sa.Boolean(), nullable=True),
    # sa.Column('order_id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.Column('type', sa.String(), nullable=True),
    # sa.Column('address', sa.String(), nullable=True),
    # sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_offer_id'), 'offer', ['id'], unique=False)
    # op.create_table('feedback',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('created', sa.DateTime(), nullable=False),
    # sa.Column('text', sa.String(), nullable=True),
    # sa.Column('rate', sa.Integer(), nullable=True),
    # sa.Column('is_offer', sa.Boolean(), nullable=False),
    # sa.Column('offer_id', sa.Integer(), nullable=True),
    # sa.Column('subject_id', sa.Integer(), nullable=True),
    # sa.Column('object_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['object_id'], ['user.id'], ),
    # sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    # sa.ForeignKeyConstraint(['subject_id'], ['user.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    # op.create_index(op.f('ix_feedback_object_id'), 'feedback', ['object_id'], unique=False)
    # op.create_index(op.f('ix_feedback_subject_id'), 'feedback', ['subject_id'], unique=False)
    # op.create_table('notification',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('created', sa.DateTime(), nullable=True),
    # sa.Column('title', sa.String(), nullable=True),
    # sa.Column('body', sa.String(), nullable=True),
    # sa.Column('user_id', sa.Integer(), nullable=True),
    # sa.Column('icon', sa.String(), nullable=True),
    # sa.Column('order_id', sa.Integer(), nullable=True),
    # sa.Column('offer_id', sa.Integer(), nullable=True),
    # sa.Column('stage', sa.Integer(), nullable=True),
    # sa.Column('is_read', sa.Boolean(), nullable=False),
    # sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_notification_body'), 'notification', ['body'], unique=False)
    # op.create_index(op.f('ix_notification_created'), 'notification', ['created'], unique=False)
    # op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    # op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    # op.create_index(op.f('ix_notification_offer_id'), 'notification', ['offer_id'], unique=False)
    # op.create_index(op.f('ix_notification_order_id'), 'notification', ['order_id'], unique=False)
    # op.create_index(op.f('ix_notification_stage'), 'notification', ['stage'], unique=False)
    # op.create_index(op.f('ix_notification_title'), 'notification', ['title'], unique=False)
    # op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    # op.add_column('order', sa.Column('type', sa.String(), nullable=True))
    # op.drop_column('order', 'service_type')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('service_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('order', 'type')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_title'), table_name='notification')
    op.drop_index(op.f('ix_notification_stage'), table_name='notification')
    op.drop_index(op.f('ix_notification_order_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_offer_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_is_read'), table_name='notification')
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_created'), table_name='notification')
    op.drop_index(op.f('ix_notification_body'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_feedback_subject_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_object_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_offer_id'), table_name='offer')
    op.drop_table('offer')
    # ### end Alembic commands ###
