"""Add columns for user psychotype

Revision ID: 49a76f07d63c
Revises: 34f31245535f
Create Date: 2022-04-28 08:59:11.130208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '49a76f07d63c'
down_revision = '34f31245535f'
branch_labels = None
depends_on = None


def upgrade():

    shape = postgresql.ENUM('square', 'triangle', 'circle', 'polyline', name='shape')
    shape.create(op.get_bind())
    color = postgresql.ENUM('gray', 'black', 'yellow', 'brown', 'blue', 'red', 'orange', 'green', name='color')
    color.create(op.get_bind())
    age_group = postgresql.ENUM('first', 'second', 'third', 'fourth', name='agegroup')
    age_group.create(op.get_bind())


    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('shape', sa.Enum('square', 'triangle', 'circle', 'polyline', name='shape'), nullable=True))
    op.add_column('user', sa.Column('color', sa.Enum('gray', 'black', 'yellow', 'brown', 'blue', 'red', 'orange', 'green', name='color'), nullable=True))
    op.add_column('user', sa.Column('age_group', sa.Enum('first', 'second', 'third', 'fourth', name='agegroup'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    
    shape = postgresql.ENUM('square', 'triangle', 'circle', 'polyline', name='shape')
    shape.drop(op.get_bind())
    color = postgresql.ENUM('gray', 'black', 'yellow', 'brown', 'blue', 'red', 'orange', 'green', name='color')
    color.drop(op.get_bind())
    age_group = postgresql.ENUM('first', 'second', 'third', 'fourth', name='agegroup')
    age_group.drop(op.get_bind())


    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age_group')
    op.drop_column('user', 'color')
    op.drop_column('user', 'shape')
    # ### end Alembic commands ###
