"""delate dating profile dislake

Revision ID: 4be69803fc42
Revises: 81d81824f114
Create Date: 2024-11-11 11:47:56.339012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4be69803fc42'
down_revision = '81d81824f114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profiledislike_id', table_name='profiledislike')
    op.drop_index('ix_profiledislike_time_not_show', table_name='profiledislike')
    op.drop_table('profiledislike')
    # op.drop_table('spatial_ref_sys')
    op.add_column('profilelike', sa.Column('like', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profilelike', 'like')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.create_table('profiledislike',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('disliker_dating_profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('disliked_dating_profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_not_show', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['disliked_dating_profile_id'], ['datingprofile.id'], name='profiledislike_disliked_dating_profile_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disliker_dating_profile_id'], ['datingprofile.id'], name='profiledislike_disliker_dating_profile_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='profiledislike_pkey')
    )
    op.create_index('ix_profiledislike_time_not_show', 'profiledislike', ['time_not_show'], unique=False)
    op.create_index('ix_profiledislike_id', 'profiledislike', ['id'], unique=False)
    # ### end Alembic commands ###
