"""empty message

Revision ID: 4cde5e9f110b
Revises: e52ab5573c04
Create Date: 2023-02-02 11:59:19.379086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cde5e9f110b'
down_revision = 'e52ab5573c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pushnotification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pushnotification_id'), 'pushnotification', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pushnotification_id'), table_name='pushnotification')
    op.drop_table('pushnotification')
    # ### end Alembic commands ###
