"""empty message

Revision ID: 4db743d0e985
Revises: 989a73cf1ef3
Create Date: 2023-01-22 09:23:24.974754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db743d0e985'
down_revision = '989a73cf1ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_story_is_prof', table_name='story')
    op.drop_column('story', 'is_prof')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('is_prof', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_story_is_prof', 'story', ['is_prof'], unique=False)
    # ### end Alembic commands ###
