"""empty message

Revision ID: 50146540f6f2
Revises: 64a3fd3b9d20
Create Date: 2023-03-28 10:44:51.153644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50146540f6f2'
down_revision = '64a3fd3b9d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritestory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favoritestory_created'), 'favoritestory', ['created'], unique=False)
    op.create_index(op.f('ix_favoritestory_id'), 'favoritestory', ['id'], unique=False)
    op.create_index(op.f('ix_favoritestory_story_id'), 'favoritestory', ['story_id'], unique=False)
    op.create_index(op.f('ix_favoritestory_user_id'), 'favoritestory', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favoritestory_user_id'), table_name='favoritestory')
    op.drop_index(op.f('ix_favoritestory_story_id'), table_name='favoritestory')
    op.drop_index(op.f('ix_favoritestory_id'), table_name='favoritestory')
    op.drop_index(op.f('ix_favoritestory_created'), table_name='favoritestory')
    op.drop_table('favoritestory')
    # ### end Alembic commands ###
