"""Add column gender to User model

Revision ID: 518669587a45
Revises: f0d4ee1f6b79
Create Date: 2022-05-19 13:59:49.494397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '518669587a45'
down_revision = 'f0d4ee1f6b79'
branch_labels = None
depends_on = None


def upgrade():

    gender = postgresql.ENUM('male','female',name='gender')
    gender.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=True))
    # ### end Alembic commands ###


def downgrade():

    gender = postgresql.ENUM('male','female',name='gender')
    gender.drop(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
