"""add colum noti

Revision ID: 51c366c962c6
Revises: c1c06d65b2f2
Create Date: 2024-12-10 10:39:47.102797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c366c962c6'
down_revision = 'c1c06d65b2f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('notification', sa.Column('link', sa.String(), nullable=True))
    op.create_index(op.f('ix_notification_icon'), 'notification', ['icon'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_icon'), table_name='notification')
    op.drop_column('notification', 'link')
    # ### end Alembic commands ###
