"""add column created for device

Revision ID: 53aebc4ad258
Revises: 78b8f33aaf90
Create Date: 2022-06-08 07:31:56.225917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53aebc4ad258'
down_revision = '78b8f33aaf90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('firebasetoken', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('firebasetoken', 'created')
    op.drop_column('device', 'created')
    # ### end Alembic commands ###
