"""empty message

Revision ID: 541b3674c9ee
Revises: d4f83b3e7ae5
Create Date: 2023-10-09 11:27:56.804450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541b3674c9ee'
down_revision = 'd4f83b3e7ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventcategory_id'), 'eventcategory', ['id'], unique=False)
    op.add_column('event', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'eventcategory', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'category_id')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_eventcategory_id'), table_name='eventcategory')
    op.drop_table('eventcategory')
    # ### end Alembic commands ###
