"""empty message

Revision ID: 543fb224b6c6
Revises: 280beb3061af
Create Date: 2023-01-21 15:35:05.052296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543fb224b6c6'
down_revision = '280beb3061af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
