"""add page model

Revision ID: 544ec3b68492
Revises: 11588734ff16
Create Date: 2022-08-12 10:36:35.434770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544ec3b68492'
down_revision = '11588734ff16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tech_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_id'), 'page', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_id'), table_name='page')
    op.drop_table('page')
    # ### end Alembic commands ###
