"""story model part 2

Revision ID: 569b0ed9f687
Revises: d1821319a009
Create Date: 2022-06-14 07:18:23.353078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569b0ed9f687'
down_revision = 'd1821319a009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('is_private', sa.Boolean(), nullable=False))
    op.add_column('story', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'story', 'topic', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'story', type_='foreignkey')
    op.drop_column('story', 'topic_id')
    op.drop_column('story', 'is_private')
    # ### end Alembic commands ###
