"""empty message

Revision ID: 5724767f21bf
Revises: 822a894b417d
Create Date: 2025-04-15 06:09:00.413240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5724767f21bf'
down_revision = '822a894b417d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excursioncategoryimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('excursion_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['excursion_category_id'], ['excursioncategory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excursioncategoryimage_excursion_category_id'), 'excursioncategoryimage', ['excursion_category_id'], unique=False)
    op.create_index(op.f('ix_excursioncategoryimage_id'), 'excursioncategoryimage', ['id'], unique=False)
    op.alter_column('excursion', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('excursion', 'ended')
    op.drop_column('excursion', 'started')
    op.add_column('excursioncategory', sa.Column('description', sa.String(), nullable=True))
    op.add_column('excursionparticipant', sa.Column('excursion_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'excursionparticipant', 'excursiongroup', ['excursion_group_id'], ['id'])
    op.add_column('excursionreview', sa.Column('created', sa.DateTime(), nullable=False))
    op.alter_column('excursionreview', 'visit_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index(op.f('ix_excursionreview_review_id'), 'excursionreview', ['review_id'], unique=False)
    op.drop_column('excursionreview', 'created_at')
    op.drop_column('member', 'is_chat_delete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('is_chat_delete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('excursionreview', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_excursionreview_review_id'), table_name='excursionreview')
    op.alter_column('excursionreview', 'visit_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('excursionreview', 'created')
    op.drop_constraint(None, 'excursionparticipant', type_='foreignkey')
    op.drop_column('excursionparticipant', 'excursion_group_id')
    op.drop_column('excursioncategory', 'description')
    op.add_column('excursion', sa.Column('started', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('excursion', sa.Column('ended', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('excursion', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_excursioncategoryimage_id'), table_name='excursioncategoryimage')
    op.drop_index(op.f('ix_excursioncategoryimage_excursion_category_id'), table_name='excursioncategoryimage')
    op.drop_table('excursioncategoryimage')
    # ### end Alembic commands ###
