"""create model StoryReport

Revision ID: 580c18f3a111
Revises: 189ca4dc59b8
Create Date: 2022-06-27 13:44:45.295636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '580c18f3a111'
down_revision = '189ca4dc59b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storyreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('is_satisfy', sa.Boolean(), nullable=True),
    sa.Column('reason', postgresql.ENUM('spam', 'nudity', 'hostility', 'violence', 'bullying', 'forbidden_product', 'intellectual_property_rights', 'suicide', 'eating_disorder', 'deceit', 'fake', name='reason', create_type=False), nullable=True),
    sa.Column('additional_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storyreport_id'), 'storyreport', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storyreport_id'), table_name='storyreport')
    op.drop_table('storyreport')
    # ### end Alembic commands ###
