"""fix dating profile

Revision ID: 59927ceee380
Revises: 4fcfce26e176
Create Date: 2024-07-29 07:31:40.869079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59927ceee380'
down_revision = '4fcfce26e176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.drop_constraint('profiledislike_disliker_dating_profile_id_fkey', 'profiledislike', type_='foreignkey')
    op.drop_constraint('profiledislike_disliked_dating_profile_id_fkey', 'profiledislike', type_='foreignkey')
    op.create_foreign_key(None, 'profiledislike', 'datingprofile', ['disliked_dating_profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'profiledislike', 'datingprofile', ['disliker_dating_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('profilefacts_subfacts_id_fkey', 'profilefacts', type_='foreignkey')
    op.drop_constraint('profilefacts_dating_profile_id_fkey', 'profilefacts', type_='foreignkey')
    op.create_foreign_key(None, 'profilefacts', 'datingprofile', ['dating_profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'profilefacts', 'facts', ['subfacts_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('profilegenremusic_sub_genre_music_id_fkey', 'profilegenremusic', type_='foreignkey')
    op.drop_constraint('profilegenremusic_dating_profile_id_fkey', 'profilegenremusic', type_='foreignkey')
    op.create_foreign_key(None, 'profilegenremusic', 'genremusic', ['sub_genre_music_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'profilegenremusic', 'datingprofile', ['dating_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('profileinterests_dating_profile_id_fkey', 'profileinterests', type_='foreignkey')
    op.drop_constraint('profileinterests_interest_id_fkey', 'profileinterests', type_='foreignkey')
    op.create_foreign_key(None, 'profileinterests', 'datingprofile', ['dating_profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'profileinterests', 'interests', ['interest_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('profilelike_liked_dating_profile_id_fkey', 'profilelike', type_='foreignkey')
    op.drop_constraint('profilelike_liker_dating_profile_id_fkey', 'profilelike', type_='foreignkey')
    op.create_foreign_key(None, 'profilelike', 'datingprofile', ['liker_dating_profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'profilelike', 'datingprofile', ['liked_dating_profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profilelike', type_='foreignkey')
    op.drop_constraint(None, 'profilelike', type_='foreignkey')
    op.create_foreign_key('profilelike_liker_dating_profile_id_fkey', 'profilelike', 'datingprofile', ['liker_dating_profile_id'], ['id'])
    op.create_foreign_key('profilelike_liked_dating_profile_id_fkey', 'profilelike', 'datingprofile', ['liked_dating_profile_id'], ['id'])
    op.drop_constraint(None, 'profileinterests', type_='foreignkey')
    op.drop_constraint(None, 'profileinterests', type_='foreignkey')
    op.create_foreign_key('profileinterests_interest_id_fkey', 'profileinterests', 'interests', ['interest_id'], ['id'])
    op.create_foreign_key('profileinterests_dating_profile_id_fkey', 'profileinterests', 'datingprofile', ['dating_profile_id'], ['id'])
    op.drop_constraint(None, 'profilegenremusic', type_='foreignkey')
    op.drop_constraint(None, 'profilegenremusic', type_='foreignkey')
    op.create_foreign_key('profilegenremusic_dating_profile_id_fkey', 'profilegenremusic', 'datingprofile', ['dating_profile_id'], ['id'])
    op.create_foreign_key('profilegenremusic_sub_genre_music_id_fkey', 'profilegenremusic', 'genremusic', ['sub_genre_music_id'], ['id'])
    op.drop_constraint(None, 'profilefacts', type_='foreignkey')
    op.drop_constraint(None, 'profilefacts', type_='foreignkey')
    op.create_foreign_key('profilefacts_dating_profile_id_fkey', 'profilefacts', 'datingprofile', ['dating_profile_id'], ['id'])
    op.create_foreign_key('profilefacts_subfacts_id_fkey', 'profilefacts', 'facts', ['subfacts_id'], ['id'])
    op.drop_constraint(None, 'profiledislike', type_='foreignkey')
    op.drop_constraint(None, 'profiledislike', type_='foreignkey')
    op.create_foreign_key('profiledislike_disliked_dating_profile_id_fkey', 'profiledislike', 'datingprofile', ['disliked_dating_profile_id'], ['id'])
    op.create_foreign_key('profiledislike_disliker_dating_profile_id_fkey', 'profiledislike', 'datingprofile', ['disliker_dating_profile_id'], ['id'])
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
