"""user pole feedback

Revision ID: 5b07a6d79d7f
Revises: 981b7647b9bf
Create Date: 2024-11-06 07:01:51.907974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b07a6d79d7f'
down_revision = '981b7647b9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('user', sa.Column('count_feedback_order', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('user', 'rating',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               server_default='0',
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'rating',
               existing_type=sa.Integer(),
               server_default=None,
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('user', 'count_feedback_order')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
