"""add colum noti

Revision ID: 5f762251d884
Revises: 65ae4f43f95c
Create Date: 2024-12-16 06:55:25.151530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f762251d884'
down_revision = '65ae4f43f95c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('message', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('message_sender_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'member', ['sender_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_sender_id_fkey', 'message', 'member', ['sender_id'], ['id'])
    op.alter_column('message', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
