"""empty message

Revision ID: 5fe490feb1a0
Revises: c2c54d9f2dd1
Create Date: 2025-04-21 13:40:28.493641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe490feb1a0'
down_revision = 'c2c54d9f2dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('excursiongroup', sa.Column('max_group_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('excursiongroup', 'max_group_size')
    # ### end Alembic commands ###
