"""detected_os for device

Revision ID: 60db230b2229
Revises: 0a226d0cdbb6
Create Date: 2022-06-09 13:21:31.417522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60db230b2229'
down_revision = '0a226d0cdbb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('detected_os', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'detected_os')
    # ### end Alembic commands ###
