"""streamable_video

Revision ID: 6196d40470a1
Revises: e2a2408f3192
Create Date: 2025-06-17 13:36:16.916982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6196d40470a1'
down_revision = 'e2a2408f3192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('is_clip', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_story_is_clip'), 'story', ['is_clip'], unique=False)
    op.add_column('storyattachment', sa.Column('is_clip', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_storyattachment_is_clip'), 'storyattachment', ['is_clip'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storyattachment_is_clip'), table_name='storyattachment')
    op.drop_column('storyattachment', 'is_clip')
    op.drop_index(op.f('ix_story_is_clip'), table_name='story')
    op.drop_column('story', 'is_clip')
    # ### end Alembic commands ###
