"""soft deleting of user

Revision ID: 62677f435dcc
Revises: 53aebc4ad258
Create Date: 2022-06-08 08:33:43.539277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62677f435dcc'
down_revision = '53aebc4ad258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deleted', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('shadow_email', sa.String(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'shadow_email')
    op.drop_column('user', 'deleted')
    # ### end Alembic commands ###
