"""empty message

Revision ID: 636580f2f97b
Revises: 1c0acd9a139a
Create Date: 2023-09-29 11:00:00.083557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636580f2f97b'
down_revision = '1c0acd9a139a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoriteorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favoriteorder_id'), 'favoriteorder', ['id'], unique=False)
    op.create_index(op.f('ix_favoriteorder_order_id'), 'favoriteorder', ['order_id'], unique=False)
    op.create_index(op.f('ix_favoriteorder_user_id'), 'favoriteorder', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_favoriteorder_user_id'), table_name='favoriteorder')
    op.drop_index(op.f('ix_favoriteorder_order_id'), table_name='favoriteorder')
    op.drop_index(op.f('ix_favoriteorder_id'), table_name='favoriteorder')
    op.drop_table('favoriteorder')
    # ### end Alembic commands ###
