"""empty message

Revision ID: 64a3fd3b9d20
Revises: a1449ce77118
Create Date: 2023-03-09 05:54:02.891180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a3fd3b9d20'
down_revision = 'a1449ce77118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('type', sa.String(), nullable=True))
    op.add_column('offer', sa.Column('address', sa.String(), nullable=True))
    op.add_column('order', sa.Column('type', sa.String(), nullable=True))
    op.drop_column('order', 'service_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('service_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('order', 'type')
    op.drop_column('offer', 'address')
    op.drop_column('offer', 'type')
    # ### end Alembic commands ###
