"""add colum noti

Revision ID: 65ae4f43f95c
Revises: 2ecd7ba75731
Create Date: 2024-12-13 07:43:25.567448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ae4f43f95c'
down_revision = '2ecd7ba75731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_initiator_id_fkey', 'chat', type_='foreignkey')
    op.drop_constraint('chat_recipient_id_fkey', 'chat', type_='foreignkey')
    op.create_foreign_key(None, 'chat', 'member', ['initiator_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat', 'member', ['recipient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.create_foreign_key('chat_recipient_id_fkey', 'chat', 'member', ['recipient_id'], ['id'])
    op.create_foreign_key('chat_initiator_id_fkey', 'chat', 'member', ['initiator_id'], ['id'])
    # ### end Alembic commands ###
