"""empty message

Revision ID: 68a8fac4d11d
Revises: a01a8b27326c
Create Date: 2022-09-27 10:58:02.672741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a8fac4d11d'
down_revision = 'a01a8b27326c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grouprequest', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grouprequest', 'is_deleted')
    # ### end Alembic commands ###
