"""add colum noti

Revision ID: 6dc0d83fd934
Revises: 1c2bfbea791d
Create Date: 2024-12-12 09:36:55.107522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc0d83fd934'
down_revision = '1c2bfbea791d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.drop_constraint('deletedmessage_member_id_fkey', 'deletedmessage', type_='foreignkey')
    op.drop_constraint('deletedmessage_message_id_fkey', 'deletedmessage', type_='foreignkey')
    op.create_foreign_key(None, 'deletedmessage', 'message', ['message_id'], ['id'])
    op.create_foreign_key(None, 'deletedmessage', 'member', ['member_id'], ['id'])
    op.drop_constraint('member_first_message_id_fkey', 'member', type_='foreignkey')
    op.drop_constraint('member_last_message_id_fkey', 'member', type_='foreignkey')
    op.create_foreign_key(None, 'member', 'message', ['last_message_id'], ['id'])
    op.create_foreign_key(None, 'member', 'message', ['first_message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.create_foreign_key('member_last_message_id_fkey', 'member', 'message', ['last_message_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('member_first_message_id_fkey', 'member', 'message', ['first_message_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'deletedmessage', type_='foreignkey')
    op.drop_constraint(None, 'deletedmessage', type_='foreignkey')
    op.create_foreign_key('deletedmessage_message_id_fkey', 'deletedmessage', 'message', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('deletedmessage_member_id_fkey', 'deletedmessage', 'member', ['member_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
