"""empty message

Revision ID: 70213839f8d7
Revises: 2f66851ac5dd
Create Date: 2023-10-05 10:21:40.538918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70213839f8d7'
down_revision = '2f66851ac5dd'
branch_labels = None
depends_on = None


def upgrade():
    ...
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###
