"""TypeChat

Revision ID: 73fd25ff2070
Revises: 5a07b87ba4cc
Create Date: 2024-12-02 06:43:39.476629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fd25ff2070'
down_revision = '5a07b87ba4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("""
        CREATE TYPE typechat AS ENUM ('personal', 'dating', 'order');
    """)

    op.add_column('chat', sa.Column('type_chat', sa.Enum('personal', 'dating', 'order', name='typechat'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'type_chat')

    # Удаляем тип typechat из базы данных
    op.execute("""
        DROP TYPE typechat;
    """)
    
    # ### end Alembic commands ###
