"""add relationship dating type

Revision ID: 74a12beffef0
Revises: 4be69803fc42
Create Date: 2024-11-12 06:36:23.259122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a12beffef0'
down_revision = '4be69803fc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')

    # Создаем тип данных relationshiptype
    op.execute("""
        CREATE TYPE relationshiptype AS ENUM (
            'friendly_communication',
            'romantic_relationships',
            'any_relationship'
        );
    """)

    # Добавляем столбец relationship_type в таблицу datingprofile
    op.add_column('datingprofile', sa.Column('relationship_type', sa.Enum('friendly_communication', 'romantic_relationships', 'any_relationship', name='relationshiptype'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datingprofile', 'relationship_type')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
