"""empty message

Revision ID: 7753fb1ddd8b
Revises: 8cec9db1c1c2
Create Date: 2023-01-21 15:08:37.207186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7753fb1ddd8b'
down_revision = '8cec9db1c1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('my_offers_count', sa.Integer(), nullable=True))
    op.alter_column('user', 'rating',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('user', 'created_orders_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'completed_orders_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user', 'my_orders_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('my_orders_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('user', 'completed_orders_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'created_orders_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'rating',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('user', 'my_offers_count')
    # ### end Alembic commands ###
