"""empty message

Revision ID: 781d918884e4
Revises: 0faf601e0cbc
Create Date: 2023-08-16 09:44:21.406742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781d918884e4'
down_revision = '0faf601e0cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('is_auto_recreate', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'is_auto_recreate')
    # ### end Alembic commands ###
