"""delete column created for device

Revision ID: 78b8f33aaf90
Revises: f1991f16b7a0
Create Date: 2022-06-08 07:30:56.228800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b8f33aaf90'
down_revision = 'f1991f16b7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'created')
    op.drop_column('firebasetoken', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firebasetoken', sa.Column('created', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('device', sa.Column('created', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
