"""empty message

Revision ID: 79d8c2a4583b
Revises: 873a9ce5662f
Create Date: 2023-02-20 15:04:30.588707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d8c2a4583b'
down_revision = '873a9ce5662f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_business', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_business')
    # ### end Alembic commands ###
