"""add colum promo order

Revision ID: 7ceab8697d87
Revises: 5f762251d884
Create Date: 2024-12-25 05:56:16.685614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ceab8697d87'
down_revision = '5f762251d884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promoorder', sa.Column('info_id', sa.Integer(), nullable=True))
    op.drop_constraint('promoorder_story_id_fkey', 'promoorder', type_='foreignkey')
    op.create_foreign_key(None, 'promoorder', 'info', ['info_id'], ['id'])
    op.drop_column('promoorder', 'story_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promoorder', sa.Column('story_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'promoorder', type_='foreignkey')
    op.create_foreign_key('promoorder_story_id_fkey', 'promoorder', 'story', ['story_id'], ['id'])
    op.drop_column('promoorder', 'info_id')
    # ### end Alembic commands ###
