"""hotel_booking

Revision ID: 7ec56201fb1c
Revises: 2ebd5f94dea6
Create Date: 2025-05-20 13:30:11.087857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ec56201fb1c'
down_revision = '2ebd5f94dea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotelbooking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(), nullable=False),
    sa.Column('hotel_hid', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('room_name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('checkin', sa.Date(), nullable=False),
    sa.Column('checkout', sa.Date(), nullable=False),
    sa.Column('partner_order_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('NEW', 'CANCELLED', 'REJECTED', 'COMPLETED', name='hotelbookingstatus'), nullable=False),
    sa.Column('etg_pay_type', sa.String(), nullable=False),
    sa.Column('is_need_credit_card_data', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_need_cvc', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('pay_uuid', sa.String(), nullable=True),
    sa.Column('init_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotelbooking_created'), 'hotelbooking', ['created'], unique=False)
    op.create_index(op.f('ix_hotelbooking_hotel_hid'), 'hotelbooking', ['hotel_hid'], unique=False)
    op.create_index(op.f('ix_hotelbooking_id'), 'hotelbooking', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hotelbooking_id'), table_name='hotelbooking')
    op.drop_index(op.f('ix_hotelbooking_hotel_hid'), table_name='hotelbooking')
    op.drop_index(op.f('ix_hotelbooking_created'), table_name='hotelbooking')
    op.drop_table('hotelbooking')
    # ### end Alembic commands ###
