"""add RatingWeights

Revision ID: 81d81824f114
Revises: 03f480a4748d
Create Date: 2024-11-11 06:50:22.447881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d81824f114'
down_revision = '03f480a4748d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratingweights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('interest_weight', sa.FLOAT(), nullable=True),
    sa.Column('genre_music_weight', sa.FLOAT(), nullable=True),
    sa.Column('facts_weight', sa.FLOAT(), nullable=True),
    sa.Column('education_weight', sa.FLOAT(), nullable=True),
    sa.Column('work_weight', sa.FLOAT(), nullable=True),
    sa.Column('total_weights', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['datingprofile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['datingprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratingweights_id'), 'ratingweights', ['id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    op.add_column('profilelike', sa.Column('liker_estimate_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profilelike', 'liker_estimate_type')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.drop_index(op.f('ix_ratingweights_id'), table_name='ratingweights')
    op.drop_table('ratingweights')
    # ### end Alembic commands ###
