"""empty message

Revision ID: 822a894b417d
Revises: 7ceab8697d87
Create Date: 2025-04-03 13:30:15.808622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '822a894b417d'
down_revision = '7ceab8697d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excursioncategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excursioncategory_id'), 'excursioncategory', ['id'], unique=True)
    op.create_table('excursion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('started', sa.DateTime(), nullable=False),
    sa.Column('ended', sa.DateTime(), nullable=True),
    sa.Column('tips', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('max_height', sa.Float(), nullable=True),
    sa.Column('min_height', sa.Float(), nullable=True),
    sa.Column('route_length', sa.Float(), nullable=True),
    sa.Column('max_group_size', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('excursion_status', postgresql.ENUM('OPEN', 'CLOSED', name='excursionstatus'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['excursioncategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excursion_created'), 'excursion', ['created'], unique=False)
    op.create_index(op.f('ix_excursion_id'), 'excursion', ['id'], unique=False)
    op.create_table('excursiongroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('excursion_id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('status', postgresql.ENUM('AVAILABLE', 'REGISTRATION', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='groupstatus'), nullable=False),
    sa.Column('current_participants', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['excursion_id'], ['excursion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excursiongroup_id'), 'excursiongroup', ['id'], unique=False)
    op.create_table('excursionimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('excursion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['excursion_id'], ['excursion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excursionimage_excursion_id'), 'excursionimage', ['excursion_id'], unique=False)
    op.create_index(op.f('ix_excursionimage_id'), 'excursionimage', ['id'], unique=False)
    op.create_table('excursionparticipant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('excursion_id', sa.Integer(), nullable=False),
    sa.Column('excursion_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['excursion_id'], ['excursion.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['excursion_group_id'], ['excursiongroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excursionparticipant_id'), 'excursionparticipant', ['id'], unique=False)
    op.create_table('excursionreview',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('excursion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['excursion_id'], ['excursion.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('excursionreview')
    op.drop_index(op.f('ix_excursionparticipant_id'), table_name='excursionparticipant')
    op.drop_table('excursionparticipant')
    op.drop_index(op.f('ix_excursionimage_id'), table_name='excursionimage')
    op.drop_index(op.f('ix_excursionimage_excursion_id'), table_name='excursionimage')
    op.drop_table('excursionimage')
    op.drop_index(op.f('ix_excursiongroup_id'), table_name='excursiongroup')
    op.drop_table('excursiongroup')
    op.drop_index(op.f('ix_excursion_id'), table_name='excursion')
    op.drop_index(op.f('ix_excursion_created'), table_name='excursion')
    op.drop_table('excursion')
    op.drop_index(op.f('ix_excursioncategory_id'), table_name='excursioncategory')
    op.drop_table('excursioncategory')
    # ### end Alembic commands ###
