"""empty message

Revision ID: 829ff8cfafbc
Revises: ab26d9fff008
Create Date: 2023-09-04 10:48:57.786770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829ff8cfafbc'
down_revision = 'ab26d9fff008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pushnotification', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pushnotification', 'link')
    # ### end Alembic commands ###
