"""empty message

Revision ID: 82e911f24481
Revises: 21a1e70493b8
Create Date: 2023-02-25 11:05:35.199868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e911f24481'
down_revision = '21a1e70493b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('address', sa.String(), nullable=True))
    op.add_column('order', sa.Column('service_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'service_type')
    op.drop_column('order', 'address')
    # ### end Alembic commands ###
