"""empty message

Revision ID: 873a9ce5662f
Revises: c0993b119807
Create Date: 2023-02-20 10:10:42.918528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873a9ce5662f'
down_revision = 'c0993b119807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('object_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_feedback_object_id'), 'feedback', ['object_id'], unique=False)
    op.create_index(op.f('ix_feedback_subject_id'), 'feedback', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'feedback', 'user', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'feedback', 'user', ['object_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_index(op.f('ix_feedback_subject_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_object_id'), table_name='feedback')
    op.drop_column('feedback', 'object_id')
    op.drop_column('feedback', 'subject_id')
    # ### end Alembic commands ###
