"""personal expirience 2

Revision ID: 87efa3a1335a
Revises: b73e47952be0
Create Date: 2022-05-24 13:44:08.954319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87efa3a1335a'
down_revision = 'b73e47952be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personalexperience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personalexperience_id'), 'personalexperience', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personalexperience_id'), table_name='personalexperience')
    op.drop_table('personalexperience')
    # ### end Alembic commands ###
