"""empty message

Revision ID: 87ff78c380c9
Revises: c9dca2989084
Create Date: 2023-01-22 14:43:49.078870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ff78c380c9'
down_revision = 'c9dca2989084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('is_block', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'is_block')
    # ### end Alembic commands ###
