"""Add hashtag model

Revision ID: 89757a082286
Revises: 60db230b2229
Create Date: 2022-06-10 08:02:00.687251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89757a082286'
down_revision = '60db230b2229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hashtag_id'), 'hashtag', ['id'], unique=False)
    op.create_index(op.f('ix_hashtag_text'), 'hashtag', ['text'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hashtag_text'), table_name='hashtag')
    op.drop_index(op.f('ix_hashtag_id'), table_name='hashtag')
    op.drop_table('hashtag')
    # ### end Alembic commands ###
