"""empty message

Revision ID: 898ea77bf02e
Revises: 483dd06a5882
Create Date: 2023-04-13 07:51:09.247817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898ea77bf02e'
down_revision = '483dd06a5882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
