"""referrers

Revision ID: 90a537dd34be
Revises: f58bfa9b10c0
Create Date: 2022-05-24 14:23:43.521908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a537dd34be'
down_revision = 'f58bfa9b10c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('referrer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['referrer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'referrer_id')
    op.drop_column('user', 'created')
    # ### end Alembic commands ###
