"""empty message

Revision ID: 989a73cf1ef3
Revises: c471027d2bcf
Create Date: 2023-01-22 09:17:40.953793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989a73cf1ef3'
down_revision = 'c471027d2bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_topic_id', table_name='topic')
    op.drop_index('ix_topic_name', table_name='topic')
    op.drop_index('ix_hashtag_topic_id', table_name='hashtag')
    op.drop_index('ix_story_topic_id', table_name='story')
    op.drop_constraint('hashtag_topic_id_fkey', 'hashtag', type_='foreignkey')
    op.drop_constraint('story_topic_id_fkey', 'story', type_='foreignkey')
    op.drop_column('hashtag', 'topic_id')
    op.drop_column('story', 'topic_id')
    op.drop_table('topic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('story_topic_id_fkey', 'story', 'topic', ['topic_id'], ['id'])
    op.create_index('ix_story_topic_id', 'story', ['topic_id'], unique=False)
    op.add_column('hashtag', sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('hashtag_topic_id_fkey', 'hashtag', 'topic', ['topic_id'], ['id'])
    op.create_index('ix_hashtag_topic_id', 'hashtag', ['topic_id'], unique=False)
    op.create_table('topic',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='topic_pkey')
    )
    op.create_index('ix_topic_name', 'topic', ['name'], unique=False)
    op.create_index('ix_topic_id', 'topic', ['id'], unique=False)
    # ### end Alembic commands ###
