"""last visited column

Revision ID: 9c1841cf486c
Revises: 0211fe6cb497
Create Date: 2022-07-05 11:51:40.209143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1841cf486c'
down_revision = '0211fe6cb497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_visited', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_visited')
    # ### end Alembic commands ###
