"""empty message

Revision ID: 9fe94794b9d0
Revises: 898ea77bf02e
Create Date: 2023-06-19 06:07:27.187428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe94794b9d0'
down_revision = '898ea77bf02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('site', sa.String(), nullable=True))
    op.add_column('user', sa.Column('experience', sa.String(), nullable=True))
    op.add_column('user', sa.Column('company_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'company_info')
    op.drop_column('user', 'experience')
    op.drop_column('user', 'site')
    # ### end Alembic commands ###
