"""premium expiring

Revision ID: a01a8b27326c
Revises: 2dc044ddf59e
Create Date: 2022-08-24 12:40:22.441709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01a8b27326c'
down_revision = '2dc044ddf59e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_premium_before', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_premium_before')
    # ### end Alembic commands ###
