"""report model

Revision ID: a0e464dcda03
Revises: 494b49f127b9
Create Date: 2022-06-22 10:47:18.031738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e464dcda03'
down_revision = '494b49f127b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('is_satisfy', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.Enum('spam', 'nudity', 'hostility', 'violence', 'bullying', 'forbidden_product', 'intellectual_property_rights', 'suicide', 'eating_disorder', 'deceit', 'fake', name='reason'), nullable=True),
    sa.Column('additional_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_id'), 'report', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_id'), table_name='report')
    op.drop_table('report')
    # ### end Alembic commands ###
