"""empty message

Revision ID: a0f8f615c53c
Revises: db15e84ad38f
Create Date: 2023-02-21 14:18:40.327873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f8f615c53c'
down_revision = 'db15e84ad38f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('show_tel', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'show_tel')
    # ### end Alembic commands ###
