"""empty message

Revision ID: a1449ce77118
Revises: 3d6e077dfda0
Create Date: 2023-03-07 06:20:35.749904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1449ce77118'
down_revision = '3d6e077dfda0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('block_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'block_comment')
    # ### end Alembic commands ###
