"""empty message

Revision ID: a2854dc868f6
Revises: bd59911b04d6
Create Date: 2023-10-31 12:18:45.040619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2854dc868f6'
down_revision = 'bd59911b04d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('offer_order_id_fkey', 'offer', type_='foreignkey')
    op.drop_constraint('offer_user_id_fkey', 'offer', type_='foreignkey')
    op.create_foreign_key(None, 'offer', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'offer', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.create_foreign_key('offer_user_id_fkey', 'offer', 'user', ['user_id'], ['id'])
    op.create_foreign_key('offer_order_id_fkey', 'offer', 'order', ['order_id'], ['id'])
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
