"""status of lesson member

Revision ID: a52587e1218e
Revises: 5fafe48a39e4
Create Date: 2022-05-26 13:33:14.022341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a52587e1218e'
down_revision = '5fafe48a39e4'
branch_labels = None
depends_on = None


def upgrade():

    status = postgresql.ENUM('stop', 'active', 'wait', name='memberstatus')
    status.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessonmember', sa.Column('status', sa.Enum('stop', 'active', 'wait', name='memberstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade():

    status = postgresql.ENUM('stop', 'active', 'wait', name='memberstatus')
    status.drop(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessonmember', 'status')
    # ### end Alembic commands ###
