"""Stories models

Revision ID: a6eecc4abf59
Revises: 308512aa84cd
Create Date: 2022-06-10 12:57:20.922451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6eecc4abf59'
down_revision = '308512aa84cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_id'), 'story', ['id'], unique=False)
    op.create_table('storyattachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_link', sa.String(), nullable=False),
    sa.Column('cover_link', sa.String(), nullable=True),
    sa.Column('is_image', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storyattachment_id'), 'storyattachment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storyattachment_id'), table_name='storyattachment')
    op.drop_table('storyattachment')
    op.drop_index(op.f('ix_story_id'), table_name='story')
    op.drop_table('story')
    # ### end Alembic commands ###
