"""hotel_free_cancellation

Revision ID: a75235cf07d7
Revises: 7ec56201fb1c
Create Date: 2025-05-22 09:26:00.400387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a75235cf07d7'
down_revision = '7ec56201fb1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotelbooking', sa.Column('has_free_cancellation', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('hotelbooking', sa.Column('free_cancellation_before', sa.DateTime(), nullable=True))
    op.execute("ALTER TYPE hotelbookingstatus ADD VALUE 'processing'")
    op.execute("ALTER TYPE hotelbookingstatus ADD VALUE 'api_error'")
    op.execute("ALTER TYPE hotelbookingstatus ADD VALUE 'pay_error'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotelbooking', 'free_cancellation_before')
    op.drop_column('hotelbooking', 'has_free_cancellation')
    op.execute("ALTER TABLE hotelbooking ALTER COLUMN status TYPE TEXT")
    op.execute("DROP TYPE hotelbookingstatus")
    op.execute("CREATE TYPE hotelbookingstatus AS ENUM('NEW', 'CANCELLED', 'REJECTED', 'COMPLETED')")
    op.execute("ALTER TABLE hotelbooking ALTER COLUMN status TYPE hotelbookingstatus USING status::hotelbookingstatus")
    # ### end Alembic commands ###
