"""Add columns out_id and link

Revision ID: a98e4a549913
Revises: 5256f99b5c05
Create Date: 2022-06-03 06:33:01.694467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a98e4a549913'
down_revision = '5256f99b5c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('out_id', sa.String(), nullable=True))
    op.add_column('lesson', sa.Column('out_id', sa.String(), nullable=True))
    op.add_column('lessonmember', sa.Column('link', sa.String(), nullable=True))
    op.add_column('lessonmember', sa.Column('out_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessonmember', 'out_id')
    op.drop_column('lessonmember', 'link')
    op.drop_column('lesson', 'out_id')
    op.drop_column('group', 'out_id')
    # ### end Alembic commands ###
