"""empty message

Revision ID: aa97696da163
Revises: 5fe490feb1a0
Create Date: 2025-04-30 12:47:08.717898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa97696da163'
down_revision = '5fe490feb1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'two_gis_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'two_gis_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
