"""empty message

Revision ID: ab26d9fff008
Revises: a376c6ae1b4c
Create Date: 2023-08-22 13:10:26.317191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab26d9fff008'
down_revision = 'a376c6ae1b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counter_id'), 'counter', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_counter_id'), table_name='counter')
    op.drop_table('counter')
    # ### end Alembic commands ###
