"""attachment note

Revision ID: abc1a3a045b5
Revises: 1a1ce8cb8e75
Create Date: 2022-08-19 13:37:14.464018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc1a3a045b5'
down_revision = '1a1ce8cb8e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachment', 'note')
    # ### end Alembic commands ###
