"""rename column is_premium in story

Revision ID: b50371cef47e
Revises: 569b0ed9f687
Create Date: 2022-06-16 11:26:43.880564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50371cef47e'
down_revision = '569b0ed9f687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('is_prof', sa.Boolean(), nullable=True))
    op.drop_column('story', 'is_premium')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('is_premium', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('story', 'is_prof')
    # ### end Alembic commands ###
