"""personal expirience

Revision ID: b73e47952be0
Revises: 2c87c97bbec5
Create Date: 2022-05-24 12:10:46.718523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b73e47952be0'
down_revision = '2c87c97bbec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
