"""Add column self_description to User model

Revision ID: bb7c0e2b1b60
Revises: 22caf7e883bf
Create Date: 2022-05-19 14:38:50.132304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7c0e2b1b60'
down_revision = '22caf7e883bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('self_desc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'self_desc')
    # ### end Alembic commands ###
