"""more geneneralisation bonuses

Revision ID: bd7a47bf54b7
Revises: 38fed0f6e6cc
Create Date: 2022-07-14 11:41:05.127130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7a47bf54b7'
down_revision = '38fed0f6e6cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus', sa.Column('recipient_id', sa.Integer(), nullable=False))
    op.add_column('bonus', sa.Column('tech_name', sa.String(), nullable=True))
    op.add_column('bonus', sa.Column('additional_user_id', sa.Integer(), nullable=True))
    op.add_column('bonus', sa.Column('object_id', sa.Integer(), nullable=True))
    op.add_column('bonus', sa.Column('object_type', sa.String(), nullable=True))
    op.drop_constraint('bonus_user_id_fkey', 'bonus', type_='foreignkey')
    op.create_foreign_key(None, 'bonus', 'user', ['recipient_id'], ['id'])
    op.create_foreign_key(None, 'bonus', 'user', ['additional_user_id'], ['id'])
    op.drop_column('bonus', 'source_id')
    op.drop_column('bonus', 'user_id')
    op.drop_column('bonus', 'source_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonus', sa.Column('source_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bonus', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bonus', sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bonus', type_='foreignkey')
    op.drop_constraint(None, 'bonus', type_='foreignkey')
    op.create_foreign_key('bonus_user_id_fkey', 'bonus', 'user', ['user_id'], ['id'])
    op.drop_column('bonus', 'object_type')
    op.drop_column('bonus', 'object_id')
    op.drop_column('bonus', 'additional_user_id')
    op.drop_column('bonus', 'tech_name')
    op.drop_column('bonus', 'recipient_id')
    # ### end Alembic commands ###
