"""empty message

Revision ID: be05e07355c2
Revises: cb538bea307e
Create Date: 2025-05-06 13:50:00.313666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be05e07355c2'
down_revision = 'cb538bea307e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('is_blocker', sa.Boolean(), nullable=True))
    op.add_column('member', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'is_blocked')
    op.drop_column('member', 'is_blocker')
    # ### end Alembic commands ###
