"""empty message

Revision ID: bfee7ec1b2c7
Revises: 79d8c2a4583b
Create Date: 2023-02-21 10:15:21.371808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfee7ec1b2c7'
down_revision = '79d8c2a4583b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whitetel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tel', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whitetel_id'), 'whitetel', ['id'], unique=False)
    op.create_index(op.f('ix_whitetel_tel'), 'whitetel', ['tel'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whitetel_tel'), table_name='whitetel')
    op.drop_index(op.f('ix_whitetel_id'), table_name='whitetel')
    op.drop_table('whitetel')
    # ### end Alembic commands ###
