"""del colum noti

Revision ID: c1c06d65b2f2
Revises: 0ab8c136bcfa
Create Date: 2024-12-10 08:04:22.652035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c06d65b2f2'
down_revision = '0ab8c136bcfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'icon',
                    existing_type=sa.String(),
                    nullable=True,
                    server_default=None)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'icon',
                    existing_type=sa.String(),
                    nullable=True,
                    server_default='default_value')  # Укажите здесь старое дефолтное значение
    # ### end Alembic commands ###