"""add chat column is_delete

Revision ID: c1c87d31cc4e
Revises: 73fd25ff2070
Create Date: 2024-12-02 10:09:27.055076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c87d31cc4e'
down_revision = '73fd25ff2070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('chat', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'is_delete')
    
    # ### end Alembic commands ###
