"""RatingWeights

Revision ID: c20e45433dcf
Revises: 74a12beffef0
Create Date: 2024-11-13 10:09:44.294086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20e45433dcf'
down_revision = '74a12beffef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('ratingweights', sa.Column('films_weight', sa.FLOAT(), nullable=True))
    op.add_column('ratingweights', sa.Column('book_weight', sa.FLOAT(), nullable=True))
    op.add_column('ratingweights', sa.Column('about_weight', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratingweights', 'about_weight')
    op.drop_column('ratingweights', 'book_weight')
    op.drop_column('ratingweights', 'films_weight')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
