"""empty message

Revision ID: c2c54d9f2dd1
Revises: 1415b2a1f21a
Create Date: 2025-04-21 09:15:29.850716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2c54d9f2dd1'
down_revision = '1415b2a1f21a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('two_gis_url', sa.String(), nullable=False),
    sa.Column('loyalty_program', sa.Boolean(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('avg_check', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('work_hours_weekdays', sa.String(), nullable=True),
    sa.Column('work_hours_weekends', sa.String(), nullable=True),
    sa.Column('delivery', sa.Boolean(), nullable=False),
    sa.Column('type', postgresql.ENUM('RESTAURANT', 'BAR', 'CAFE', name='restauranttype'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_id'), 'restaurant', ['id'], unique=False)
    op.create_table('restaurantimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurantimage_id'), 'restaurantimage', ['id'], unique=False)
    op.create_index(op.f('ix_restaurantimage_restaurant_id'), 'restaurantimage', ['restaurant_id'], unique=False)
    op.create_table('restaurantphonenumber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurantphonenumber_id'), 'restaurantphonenumber', ['id'], unique=False)
    op.create_index(op.f('ix_restaurantphonenumber_restaurant_id'), 'restaurantphonenumber', ['restaurant_id'], unique=False)
    op.create_table('restaurantreview',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurantreview_id'), 'restaurantreview', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurantreview_id'), table_name='restaurantreview')
    op.drop_table('restaurantreview')
    op.drop_index(op.f('ix_restaurantphonenumber_restaurant_id'), table_name='restaurantphonenumber')
    op.drop_index(op.f('ix_restaurantphonenumber_id'), table_name='restaurantphonenumber')
    op.drop_table('restaurantphonenumber')
    op.drop_index(op.f('ix_restaurantimage_restaurant_id'), table_name='restaurantimage')
    op.drop_index(op.f('ix_restaurantimage_id'), table_name='restaurantimage')
    op.drop_table('restaurantimage')
    op.drop_index(op.f('ix_restaurant_id'), table_name='restaurant')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
