"""empty message

Revision ID: c73bef42745b
Revises: dd4741e117a1
Create Date: 2025-04-18 04:54:06.675055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c73bef42745b'
down_revision = 'dd4741e117a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excursionbooking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('NEW', 'PAID', 'REJECTED', 'FINISHED', name='excursionbookingstatus'), nullable=False),
    sa.Column('excursion_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['excursion_id'], ['excursion.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['excursiongroup.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment')
    )
    op.create_index(op.f('ix_excursionbooking_id'), 'excursionbooking', ['id'], unique=False)
    op.drop_constraint('excursionmember_booking_id_fkey', 'excursionmember', type_='foreignkey')
    op.create_foreign_key(None, 'excursionmember', 'excursionbooking', ['booking_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'excursionmember', type_='foreignkey')
    op.create_foreign_key('excursionmember_booking_id_fkey', 'excursionmember', 'user', ['booking_id'], ['id'])
    op.drop_index(op.f('ix_excursionbooking_id'), table_name='excursionbooking')
    op.drop_table('excursionbooking')
    # ### end Alembic commands ###
