"""empty message

Revision ID: cb538bea307e
Revises: aa97696da163
Create Date: 2025-05-06 07:15:15.681330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb538bea307e'
down_revision = 'aa97696da163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('passengers_quantity', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('ECONOMY', 'COMFORT', 'BUSINESS', 'VIP', 'MINIVAN', name='transfertype'), nullable=False),
    sa.Column('child_seat', sa.Boolean(), nullable=True),
    sa.Column('animal', sa.Boolean(), nullable=True),
    sa.Column('ski_supplies', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_id'), 'transfer', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_id'), table_name='transfer')
    op.drop_table('transfer')
    # ### end Alembic commands ###
