"""fix dating profile

Revision ID: cd44f07a6c7d
Revises: 120d8c14105a
Create Date: 2024-07-04 10:25:03.966584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd44f07a6c7d'
down_revision = '120d8c14105a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datingprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('films', sa.String(), nullable=True),
    sa.Column('book', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('work', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datingprofile_id'), 'datingprofile', ['id'], unique=False)
    op.create_table('profileinterests',
    sa.Column('dating_profile_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dating_profile_id'], ['datingprofile.id'], ),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ),
    sa.PrimaryKeyConstraint('dating_profile_id', 'interest_id')
    )
    # op.drop_table('spatial_ref_sys')
    op.drop_index('ix_dating_profile_id', table_name='dating_profile')
    op.execute('DROP TABLE dating_profile CASCADE')  # Используем op.execute для выполнения SQL-команды с CASCADE
    op.execute('DROP TABLE profile_interests CASCADE')  # Используем op.execute для выполнения SQL-команды с CASCADE
    op.add_column('user', sa.Column('is_dating_profile', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_dating_profile')
    op.create_table('profile_interests',
    sa.Column('dating_profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interest_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dating_profile_id'], ['dating_profile.id'], name='profile_interests_dating_profile_id_fkey'),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], name='profile_interests_interest_id_fkey'),
    sa.PrimaryKeyConstraint('dating_profile_id', 'interest_id', name='profile_interests_pkey')
    )
    op.create_table('dating_profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('films', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('book', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('about', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('education', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('work', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='dating_profile_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dating_profile_pkey')
    )
    op.create_index('ix_dating_profile_id', 'dating_profile', ['id'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('profileinterests')
    op.drop_index(op.f('ix_datingprofile_id'), table_name='datingprofile')
    op.drop_table('datingprofile')
    # ### end Alembic commands ###
