"""empty message

Revision ID: d1c4b4a25b29
Revises: 50146540f6f2
Create Date: 2023-03-29 07:49:25.433932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c4b4a25b29'
down_revision = '50146540f6f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serviceinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serviceinfo_created'), 'serviceinfo', ['created'], unique=False)
    op.create_index(op.f('ix_serviceinfo_id'), 'serviceinfo', ['id'], unique=False)
    op.create_index(op.f('ix_serviceinfo_slug'), 'serviceinfo', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_serviceinfo_slug'), table_name='serviceinfo')
    op.drop_index(op.f('ix_serviceinfo_id'), table_name='serviceinfo')
    op.drop_index(op.f('ix_serviceinfo_created'), table_name='serviceinfo')
    op.drop_table('serviceinfo')
    # ### end Alembic commands ###
