"""empty message

Revision ID: d4f83b3e7ae5
Revises: 70213839f8d7
Create Date: 2023-10-05 10:26:08.068293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f83b3e7ae5'
down_revision = '70213839f8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cover', sa.String(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('reward', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievement_created'), 'achievement', ['created'], unique=False)
    op.create_index(op.f('ix_achievement_id'), 'achievement', ['id'], unique=False)
    op.create_index(op.f('ix_achievement_name'), 'achievement', ['name'], unique=False)
    op.create_table('userachievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userachievement_achievement_id'), 'userachievement', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_userachievement_id'), 'userachievement', ['id'], unique=False)
    op.create_index(op.f('ix_userachievement_user_id'), 'userachievement', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_userachievement_user_id'), table_name='userachievement')
    op.drop_index(op.f('ix_userachievement_id'), table_name='userachievement')
    op.drop_index(op.f('ix_userachievement_achievement_id'), table_name='userachievement')
    op.drop_table('userachievement')
    op.drop_index(op.f('ix_achievement_name'), table_name='achievement')
    op.drop_index(op.f('ix_achievement_id'), table_name='achievement')
    op.drop_index(op.f('ix_achievement_created'), table_name='achievement')
    op.drop_table('achievement')
    # ### end Alembic commands ###
