"""Story View Model

Revision ID: d868573afe0a
Revises: b50371cef47e
Create Date: 2022-06-20 08:09:09.682865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd868573afe0a'
down_revision = 'b50371cef47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
