"""add column extra, and member

Revision ID: d8d615f69203
Revises: 7d859bc0668a
Create Date: 2024-12-03 07:52:25.230192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d615f69203'
down_revision = '7d859bc0668a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('member', sa.Column('first_message_id', sa.Integer(), nullable=True))
    op.add_column('member', sa.Column('ended', sa.DateTime(), nullable=True))
    op.add_column('member', sa.Column('started', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_member_created'), 'member', ['created'], unique=False)
    op.create_index(op.f('ix_member_ended'), 'member', ['ended'], unique=False)
    op.create_index(op.f('ix_member_first_message_id'), 'member', ['first_message_id'], unique=False)
    op.create_index(op.f('ix_member_started'), 'member', ['started'], unique=False)
    op.create_foreign_key(None, 'member', 'message', ['first_message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('is_chat_delete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.drop_index(op.f('ix_member_started'), table_name='member')
    op.drop_index(op.f('ix_member_first_message_id'), table_name='member')
    op.drop_index(op.f('ix_member_ended'), table_name='member')
    op.drop_index(op.f('ix_member_created'), table_name='member')
    op.drop_column('member', 'started')
    op.drop_column('member', 'ended')
    op.drop_column('member', 'first_message_id')
    op.drop_column('member', 'created')
    # ### end Alembic commands ###
