"""empty message

Revision ID: dc93627c148a
Revises: 87ff78c380c9
Create Date: 2023-01-24 15:02:28.129365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc93627c148a'
down_revision = '87ff78c380c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
