"""empty message

Revision ID: dd4741e117a1
Revises: fe18f13afbbb
Create Date: 2025-04-17 13:14:45.278774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd4741e117a1'
down_revision = 'fe18f13afbbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excursionmember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('excursion_group_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('is_adult', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['excursion_group_id'], ['excursiongroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excursionmember_id'), 'excursionmember', ['id'], unique=False)
    op.drop_index('ix_excursionparticipant_id', table_name='excursionparticipant')
    op.drop_table('excursionparticipant')
    op.add_column('excursiongroup', sa.Column('current_members', sa.Integer(), nullable=False))
    op.alter_column('excursiongroup', 'ended',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('excursiongroup', 'current_participants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('excursiongroup', sa.Column('current_participants', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('excursiongroup', 'ended',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('excursiongroup', 'current_members')
    op.create_table('excursionparticipant',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('excursion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('excursion_group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['excursion_group_id'], ['excursiongroup.id'], name='excursionparticipant_excursion_group_id_fkey'),
    sa.ForeignKeyConstraint(['excursion_id'], ['excursion.id'], name='excursionparticipant_excursion_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='excursionparticipant_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='excursionparticipant_pkey')
    )
    op.create_index('ix_excursionparticipant_id', 'excursionparticipant', ['id'], unique=False)
    op.drop_index(op.f('ix_excursionmember_id'), table_name='excursionmember')
    op.drop_table('excursionmember')
    # ### end Alembic commands ###
