"""empty message

Revision ID: df06b318ef54
Revises: ff77b305c5f7
Create Date: 2023-06-20 06:52:27.327225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df06b318ef54'
down_revision = 'ff77b305c5f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_created'), 'subscription', ['created'], unique=False)
    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_object_id'), 'subscription', ['object_id'], unique=False)
    op.create_index(op.f('ix_subscription_subject_id'), 'subscription', ['subject_id'], unique=False)
    op.add_column('serviceinfo', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serviceinfo', 'link')
    op.drop_index(op.f('ix_subscription_subject_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_object_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_created'), table_name='subscription')
    op.drop_table('subscription')
    # ### end Alembic commands ###
