"""short_story_column

Revision ID: e2a2408f3192
Revises: 0bf3b884fb3d
Create Date: 2025-06-16 07:09:35.498910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a2408f3192'
down_revision = '0bf3b884fb3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('is_short_story', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index(op.f('ix_story_is_short_story'), 'story', ['is_short_story'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_is_short_story'), table_name='story')
    op.drop_column('story', 'is_short_story')
    # ### end Alembic commands ###
