"""empty message

Revision ID: e2f47031db06
Revises: a75235cf07d7
Create Date: 2025-05-22 10:57:50.549206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f47031db06'
down_revision = 'a75235cf07d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE hotelbookingstatus ADD VALUE 'PROCESSING'")
    op.execute("ALTER TYPE hotelbookingstatus ADD VALUE 'API_ERROR'")
    op.execute("ALTER TYPE hotelbookingstatus ADD VALUE 'PAY_ERROR'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE hotelbooking ALTER COLUMN status TYPE TEXT")
    op.execute("DROP TYPE hotelbookingstatus")
    op.execute("CREATE TYPE hotelbookingstatus AS ENUM('NEW', 'CANCELLED', 'REJECTED', 'COMPLETED', 'processing', 'api_error', 'pay_error')")
    op.execute("ALTER TABLE hotelbooking ALTER COLUMN status TYPE hotelbookingstatus USING status::hotelbookingstatus")
    # ### end Alembic commands ###
