"""empty message

Revision ID: e52ab5573c04
Revises: 2cd756b4fd7a
Create Date: 2023-01-31 06:16:10.666788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52ab5573c04'
down_revision = '2cd756b4fd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('important', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info', 'important')
    # ### end Alembic commands ###
