"""Chat

Revision ID: e58c23a850e1
Revises: 1fe4eb47cff6
Create Date: 2024-11-27 06:31:46.829094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e58c23a850e1'
down_revision = '1fe4eb47cff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletedmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletedmessage_id'), 'deletedmessage', ['id'], unique=False)
    op.create_index(op.f('ix_deletedmessage_member_id'), 'deletedmessage', ['member_id'], unique=False)
    op.create_index(op.f('ix_deletedmessage_message_id'), 'deletedmessage', ['message_id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    op.drop_index('ix_contacting_created', table_name='contacting')
    op.drop_index('ix_contacting_id', table_name='contacting')
    op.drop_index('ix_contacting_processed', table_name='contacting')
    op.drop_index('ix_contacting_user_id', table_name='contacting')
    op.drop_table('contacting')
    op.drop_index('ix_messageextradatum_id', table_name='messageextradatum')
    op.drop_index('ix_messageextradatum_is_delete', table_name='messageextradatum')
    op.drop_index('ix_messageextradatum_message_id', table_name='messageextradatum')
    op.drop_index('ix_messageextradatum_user_id', table_name='messageextradatum')
    op.drop_table('messageextradatum')
    op.add_column('attachment', sa.Column('note', sa.String(), nullable=True))
    op.drop_index('ix_attachment_type', table_name='attachment')
    op.drop_index('ix_attachment_user_id', table_name='attachment')
    op.drop_constraint('attachment_user_id_fkey', 'attachment', type_='foreignkey')
    op.drop_constraint('attachment_message_id_fkey', 'attachment', type_='foreignkey')
    op.create_foreign_key(None, 'attachment', 'message', ['message_id'], ['id'])
    op.drop_column('attachment', 'user_id')
    op.drop_column('attachment', 'type')
    op.drop_index('ix_chat_chat_cover', table_name='chat')
    op.drop_index('ix_chat_chat_name', table_name='chat')
    op.drop_index('ix_chat_number', table_name='chat')
    op.drop_index('ix_chat_subtype', table_name='chat')
    op.drop_index('ix_chat_type_', table_name='chat')
    op.drop_constraint('chat_recipient_id_fkey', 'chat', type_='foreignkey')
    op.drop_constraint('chat_initiator_id_fkey', 'chat', type_='foreignkey')
    op.create_foreign_key(None, 'chat', 'member', ['recipient_id'], ['id'])
    op.create_foreign_key(None, 'chat', 'member', ['initiator_id'], ['id'])
    op.drop_column('chat', 'subtype')
    op.drop_column('chat', 'number')
    op.drop_column('chat', 'type_')
    op.drop_column('chat', 'chat_cover')
    op.drop_column('chat', 'chat_name')
    op.drop_column('chat', 'member_count')
    op.add_column('member', sa.Column('delete_before_id', sa.Integer(), nullable=True))
    op.drop_index('ix_member_chat_id', table_name='member')
    op.drop_index('ix_member_chat_name', table_name='member')
    op.drop_index('ix_member_created', table_name='member')
    op.drop_index('ix_member_ended', table_name='member')
    op.drop_index('ix_member_first_message_id', table_name='member')
    op.drop_index('ix_member_is_tech', table_name='member')
    op.drop_index('ix_member_started', table_name='member')
    op.create_index(op.f('ix_member_delete_before_id'), 'member', ['delete_before_id'], unique=False)
    op.drop_constraint('member_first_message_id_fkey', 'member', type_='foreignkey')
    op.drop_constraint('member_chat_id_fkey', 'member', type_='foreignkey')
    op.drop_constraint('member_user_id_fkey', 'member', type_='foreignkey')
    op.drop_constraint('member_last_message_id_fkey', 'member', type_='foreignkey')
    op.create_foreign_key(None, 'member', 'message', ['last_message_id'], ['id'])
    op.create_foreign_key(None, 'member', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'member', 'message', ['delete_before_id'], ['id'])
    op.drop_column('member', 'is_tech')
    op.drop_column('member', 'unread_count')
    op.drop_column('member', 'chat_id')
    op.drop_column('member', 'chat_cover')
    op.drop_column('member', 'created')
    op.drop_column('member', 'chat_name')
    op.drop_column('member', 'started')
    op.drop_column('member', 'ended')
    op.drop_column('member', 'first_message_id')
    op.add_column('message', sa.Column('text', sa.String(), nullable=True))
    op.add_column('message', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.alter_column('message', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_message_is_delete', table_name='message')
    op.drop_index('ix_message_is_event', table_name='message')
    op.drop_index('ix_message_parent_id', table_name='message')
    op.drop_index('ix_message_user_id', table_name='message')
    op.create_index(op.f('ix_message_is_read'), 'message', ['is_read'], unique=False)
    op.drop_constraint('message_parent_id_fkey', 'message', type_='foreignkey')
    op.drop_constraint('message_sender_id_fkey', 'message', type_='foreignkey')
    op.drop_constraint('message_user_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'member', ['sender_id'], ['id'])
    op.drop_column('message', 'body')
    op.drop_column('message', 'parent_id')
    op.drop_column('message', 'parent_type')
    op.drop_column('message', 'is_event')
    op.drop_column('message', 'user_id')
    op.drop_column('message', 'is_delete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_delete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('message', sa.Column('is_event', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('parent_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('message', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('message', sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_user_id_fkey', 'message', 'user', ['user_id'], ['id'])
    op.create_foreign_key('message_sender_id_fkey', 'message', 'member', ['sender_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('message_parent_id_fkey', 'message', 'message', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_message_is_read'), table_name='message')
    op.create_index('ix_message_user_id', 'message', ['user_id'], unique=False)
    op.create_index('ix_message_parent_id', 'message', ['parent_id'], unique=False)
    op.create_index('ix_message_is_event', 'message', ['is_event'], unique=False)
    op.create_index('ix_message_is_delete', 'message', ['is_delete'], unique=False)
    op.alter_column('message', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('message', 'is_read')
    op.drop_column('message', 'text')
    op.add_column('member', sa.Column('first_message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('member', sa.Column('ended', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('member', sa.Column('started', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('member', sa.Column('chat_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('member', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('member', sa.Column('chat_cover', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('member', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('member', sa.Column('unread_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('member', sa.Column('is_tech', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.create_foreign_key('member_last_message_id_fkey', 'member', 'message', ['last_message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('member_user_id_fkey', 'member', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('member_chat_id_fkey', 'member', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('member_first_message_id_fkey', 'member', 'message', ['first_message_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_member_delete_before_id'), table_name='member')
    op.create_index('ix_member_started', 'member', ['started'], unique=False)
    op.create_index('ix_member_is_tech', 'member', ['is_tech'], unique=False)
    op.create_index('ix_member_first_message_id', 'member', ['first_message_id'], unique=False)
    op.create_index('ix_member_ended', 'member', ['ended'], unique=False)
    op.create_index('ix_member_created', 'member', ['created'], unique=False)
    op.create_index('ix_member_chat_name', 'member', ['chat_name'], unique=False)
    op.create_index('ix_member_chat_id', 'member', ['chat_id'], unique=False)
    op.drop_column('member', 'delete_before_id')
    op.add_column('chat', sa.Column('member_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chat', sa.Column('chat_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('chat', sa.Column('chat_cover', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('chat', sa.Column('type_', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('chat', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chat', sa.Column('subtype', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.create_foreign_key('chat_initiator_id_fkey', 'chat', 'user', ['initiator_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('chat_recipient_id_fkey', 'chat', 'user', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_chat_type_', 'chat', ['type_'], unique=False)
    op.create_index('ix_chat_subtype', 'chat', ['subtype'], unique=False)
    op.create_index('ix_chat_number', 'chat', ['number'], unique=False)
    op.create_index('ix_chat_chat_name', 'chat', ['chat_name'], unique=False)
    op.create_index('ix_chat_chat_cover', 'chat', ['chat_cover'], unique=False)
    op.add_column('attachment', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('attachment', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.create_foreign_key('attachment_message_id_fkey', 'attachment', 'message', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('attachment_user_id_fkey', 'attachment', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index('ix_attachment_user_id', 'attachment', ['user_id'], unique=False)
    op.create_index('ix_attachment_type', 'attachment', ['type'], unique=False)
    op.drop_column('attachment', 'note')
    op.create_table('messageextradatum',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('read', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_delete', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name='messageextradatum_message_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='messageextradatum_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='messageextradatum_pkey')
    )
    op.create_index('ix_messageextradatum_user_id', 'messageextradatum', ['user_id'], unique=False)
    op.create_index('ix_messageextradatum_message_id', 'messageextradatum', ['message_id'], unique=False)
    op.create_index('ix_messageextradatum_is_delete', 'messageextradatum', ['is_delete'], unique=False)
    op.create_index('ix_messageextradatum_id', 'messageextradatum', ['id'], unique=False)
    op.create_table('contacting',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('back_contacts', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('processed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='contacting_user_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='contacting_pkey')
    )
    op.create_index('ix_contacting_user_id', 'contacting', ['user_id'], unique=False)
    op.create_index('ix_contacting_processed', 'contacting', ['processed'], unique=False)
    op.create_index('ix_contacting_id', 'contacting', ['id'], unique=False)
    op.create_index('ix_contacting_created', 'contacting', ['created'], unique=False)
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.drop_index(op.f('ix_deletedmessage_message_id'), table_name='deletedmessage')
    op.drop_index(op.f('ix_deletedmessage_member_id'), table_name='deletedmessage')
    op.drop_index(op.f('ix_deletedmessage_id'), table_name='deletedmessage')
    op.drop_table('deletedmessage')
    # ### end Alembic commands ###
