"""fix facts and music

Revision ID: e59ce7c15c15
Revises: 0db398defce2
Create Date: 2024-07-09 11:59:21.271152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59ce7c15c15'
down_revision = '0db398defce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.drop_constraint('facts_parent_facts_id_fkey', 'facts', type_='foreignkey')
    op.create_foreign_key(None, 'facts', 'facts', ['parent_facts_id'], ['id'])
    op.drop_constraint('genremusic_parent_genre_music_id_fkey', 'genremusic', type_='foreignkey')
    op.create_foreign_key(None, 'genremusic', 'genremusic', ['parent_genre_music_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genremusic', type_='foreignkey')
    op.create_foreign_key('genremusic_parent_genre_music_id_fkey', 'genremusic', 'interests', ['parent_genre_music_id'], ['id'])
    op.drop_constraint(None, 'facts', type_='foreignkey')
    op.create_foreign_key('facts_parent_facts_id_fkey', 'facts', 'interests', ['parent_facts_id'], ['id'])
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
