"""empty message

Revision ID: e8ae4b990ce4
Revises: 68a8fac4d11d
Create Date: 2022-10-04 12:50:54.246003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ae4b990ce4'
down_revision = '68a8fac4d11d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'is_read',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=False,
               postgresql_using='is_read::boolean'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'is_read',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
