"""empty message

Revision ID: f02671e51955
Revises: 4cde5e9f110b
Create Date: 2023-02-15 15:04:15.187727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02671e51955'
down_revision = '4cde5e9f110b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('in_blacklist', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user', sa.Column('in_whitelist', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'in_whitelist')
    op.drop_column('user', 'in_blacklist')
    # ### end Alembic commands ###
