"""add column extra, and member

Revision ID: f47a940da1c1
Revises: d8d615f69203
Create Date: 2024-12-03 07:57:02.578466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47a940da1c1'
down_revision = 'd8d615f69203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messageextradatum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('read', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messageextradatum_id'), 'messageextradatum', ['id'], unique=False)
    op.create_index(op.f('ix_messageextradatum_is_delete'), 'messageextradatum', ['is_delete'], unique=False)
    op.create_index(op.f('ix_messageextradatum_member_id'), 'messageextradatum', ['member_id'], unique=False)
    op.create_index(op.f('ix_messageextradatum_message_id'), 'messageextradatum', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messageextradatum_message_id'), table_name='messageextradatum')
    op.drop_index(op.f('ix_messageextradatum_member_id'), table_name='messageextradatum')
    op.drop_index(op.f('ix_messageextradatum_is_delete'), table_name='messageextradatum')
    op.drop_index(op.f('ix_messageextradatum_id'), table_name='messageextradatum')
    op.drop_table('messageextradatum')
    # ### end Alembic commands ###
