"""self analysis

Revision ID: f58bfa9b10c0
Revises: 87efa3a1335a
Create Date: 2022-05-24 14:00:45.641886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58bfa9b10c0'
down_revision = '87efa3a1335a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('self_analysis', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'self_analysis')
    # ### end Alembic commands ###
