"""empty message

Revision ID: fe18f13afbbb
Revises: 3a0f259ca98f
Create Date: 2025-04-16 10:50:27.518851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe18f13afbbb'
down_revision = '3a0f259ca98f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('excursion', 'tips',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'excursioncategory', ['name'])
    op.add_column('excursiongroup', sa.Column('started', sa.DateTime(), nullable=False))
    op.add_column('excursiongroup', sa.Column('ended', sa.DateTime(), nullable=False))
    op.drop_column('excursiongroup', 'end_datetime')
    op.drop_column('excursiongroup', 'start_datetime')
    op.create_index(op.f('ix_excursionreview_id'), 'excursionreview', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_excursionreview_id'), table_name='excursionreview')
    op.add_column('excursiongroup', sa.Column('start_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('excursiongroup', sa.Column('end_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('excursiongroup', 'ended')
    op.drop_column('excursiongroup', 'started')
    op.drop_constraint(None, 'excursioncategory', type_='unique')
    op.alter_column('excursion', 'tips',
               existing_type=sa.String(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
