"""empty message

Revision ID: ff77b305c5f7
Revises: 9fe94794b9d0
Create Date: 2023-06-19 06:48:09.061037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff77b305c5f7'
down_revision = '9fe94794b9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'confirmed_at')
    # ### end Alembic commands ###
